validatedpatterns/common

Makefile
Makefile.toplevel
site/templates/subscriptions.yaml

1) Update toplevel makefile template to match what we have in manufacturing-edge-ai-ml (which is better than the old one)
2) Update the embedded shell in the makefile to explain what it's doing and have better error checking (it was completing too early on cluster bootstrap)

Makefile fixes

---

Makefile

Found out in testing and going through the RHPDS process that `git branch --show-current` is not available on git in EL8 - so we perform the equivalent action using a more compatible mechanism instead.

Enhance compatibility with older versions of git

---

site/templates/applications.yaml

argocd errors out on sync because the values for the overrides are boolean vs boolean strings.

Adds the if control to force booleans to be string type for argo

---

site/templates/subsciptions.yaml

Adding functionality to list namespaces in the **subcriptions:** section of the values-datacenter.yaml or values-factory.yaml/
Example:  
- name: amq-streams
namespaces:
- manuela-data-lake-central-kafka-cluster
- manuela-tst-all
channel: amq-streams-1.7.x
csv: amqstreams.v1.7.1
or 
- name: advanced-cluster-management
namespace:  open-cluster-management
channel: release-2.3
csv: advanced-cluster-management.v2.3.2

Functionality for a list of namespaces for operators

---

.gitignore
Makefile
scripts/vault-utils.sh

make vault-init will now initialize and unseal a production mode vault.
The vault-utils.sh script contains a number of conveniences for manipulating a vault instance in openshift.

Add script and target to unseal vault when used in production mode

---

scripts/vault-token.sh

The script will copy the token contents out of the vault token and into a deployable resource for RHACM.
There will be another PR for mechanisms to install the other resources that the framework will need (for example, the target namespace - this must currently be created "by hand")

Add script for copying vault-token for external secrets

---

scripts/vault-utils.sh

Without this we risk to easily overwrite the seal + token file and hence
lose future access to the vault.

Protect ourselves from calling vault-init twice

---

Makefile
acm/templates/policies/application-policies.yaml
clustergroup/templates/applications.yaml
clustergroup/templates/argocd.yaml
install/templates/argocd/application.yaml

Retrieves hub cluster from configured ingress.cluster and injects it as a variable for applications to use.  This is important for services that might need to be accessed via explicit routes on the hub cluster.
We can't take this approach with managed clusters since we won't know how many there will be and we can't know when applying the template which one we're rendering for.  (We are hoping that ACM templating can help with this.)
Full credit to @mbaldessari for the approach and implementation - my only contribution here is camel-casing the variable name and making it explicitly "hub" cluster.

Add Hub cluster domain as a global variable based on ingress config

---

.gitignore
Makefile
scripts/vault-utils.sh

The makefile and scripts now know how to initialize a vault PKI for the DNS domain that is the parent of the hub cluster's domain.  (For example, the PKI for apps.mhjacks-mcgo-hub.blueprints.rhecoeng.com is created for blueprints.rhecoeng.com).

Vault PKI initialization

---

scripts/vault-utils.sh

- Fix the name of the function to initialize the kubernetes backend
- Add --interactive to the oc vault exec calls
- Add a policy init function to setup initial policy for the vault

Fix typo and add initial vault policy

---

acm/templates/policies/application-policies.yaml

This would cause ACM to error out on bootstrap with an ugly helm template error

Add variable qualification to prevent helm template errors

---

scripts/vault-utils.sh

Current wrong command:
bash-4.4$ vault secrets tune -max-lease=8760h pki
flag provided but not defined: -max-lease
Add -ttl at the end to fix it:
bash-4.4$ vault secrets tune --max-lease-ttl=8760h pki
Success! Tuned the secrets engine at: pki/

Fix TTL vault init typo

---

acm/templates/policies/application-policies.yaml

I believe the previous conditional created a situation where the conditional would always evaluate to "true", since the template would only render on the hub cluster where the variable was set to true.

Don't conditionalize lookups when we know we need them

---

scripts/vault-utils.sh

We currently uase "bash -c" inside vault_exec. This only works when
using UBI-based images. Let's move to 'sh -c' to be a bit more robust
in case we're in the presence of the upstream vault images which do not
have bash installed.
Tested a 'vault-init' on UBI images and it correctly worked with no
errors whatsoever in the log.

Remove bashism in vault_exec

---

acm/templates/policies/ocp-gitops-policy.yaml

This allows argo on regional clusters to have more rights.
Specifically this is needed to create the clusterbindingrole needed
for the k8s-external-secret operator.
As a first pass we'll use the '*' namespace. In a second iteration
we'll need to look at restricting that to openshift-gitops and the
namespace of the regional gitops instance. At this point of time
such a change is too invasive and is at risk of breaking existing
patterns.
Tested this on multicloud gitops and I correctly get argo to create
the clusterrolebinding in the k8s-external-secret:
$ oc get clusterrolebinding | grep k8s-extern
k8s-external-secrets-kubernetes-external-secrets          ClusterRole/k8s-external-secrets-kubernetes-external-secrets
k8s-external-secrets-kubernetes-external-secrets-auth …

Add namespace support to the regional gitops installations

---

scripts/vault-utils.sh

This is not portable [1] and in some shells and also on bash depending
on the version [2] it may or may not automatically interpret switches (like -n).
Let's switch to printf which is the POSIX-blessed way of doing things
[3].
Tested this on my environment and was able to still do a vault-init
without any errors.
[1] https://wiki.bash-hackers.org/scripting/nonportable#echo_command
[2] https://stackoverflow.com/questions/11193466/echo-n-prints-n
[3] https://wiki.bash-hackers.org/commands/builtin/printf

Stop using echo when returning a string in a function

---

acm/templates/policies/hub-certificate-authority.yaml
acm/values.yaml

By default this ACM templates is inactive and will only be activated if
asked explicitely via the .pushHubCA parameter.
It will pull the ca.crt field from the the kube-root-ca.crt ConfigMap on
the hub into a secret on the managed cluster. This will then be used
by the external-secrets pod so it can trust the https://vault-vault.apps.hub-domain...
API endpoint of the vault.
Tested with this change and once enabled via .pushHubCA the
kubernetes-external-secrets pod could correctly connect to the vault
running on the HUB (without this we'd get self-signed certs errors)

Add conditional hub-certificate-authority template to push HUB CA to managed clusters

---

Makefile

The repo would sometimes come out as `https///`.  With this new routine, the URL prefix is removed earlier in the process and re-added as `https://` at the very end of the sed pipeline

Fix the TARGET_REPO calculation

---

scripts/vault-utils.sh

This will change vault-init to initialize a secret container in hub and set it up for use by external secrets

Changes to vault-utils to support vault/external-secrets combo

---

scripts/vault-utils.sh

We're moving to the newer golang-based external secrets operator at https://external-secrets.io/
To be more explicit about our intention we name namespaces and
serviceaccounts golang-external-secrets. Let's rename it in the hub
config as well.
Tested with the other related golang changes and everything worked as
expected.

Rename the namespace and serviceaccounts to the name of the new golang-based external secrets operator

---

Makefile

Common is not a submodule any longer. No point in keeping this around

Remove submodule's init target

---

acm/templates/policies/application-policies.yaml
acm/templates/policies/ocp-gitops-policy.yaml
tests/acm-naked.expected.yaml
tests/acm-normal.expected.yaml

As somewhat specified in [1] there are different complianceTypes and
'musthave' does not imply that the object being applied is *identical*
to what is specified in the policy. Namely the docs for 'musthave' state:
"The other fields in the template are a subset of what exists in the object."
The actual consequence on real deployment of 'musthave' is the
following:
* Existing object
- foo
bar:
- a
- b
If the above template gets changed in ACM:
- foo
bar:
- d
- e
The end result in case of 'musthave' complianceType will be:
- foo
bar:
- a
- b
- d
- e
So let's switch to complianceType 'mustonlyhave' which actually
enforces the full object:
Indicates that an object must exist with the exact name and relevant fields.
Tested this on my multicloud environment and I could observe that
changes to …

Switch to mustonlyhave

---

Makefile

This improves the UX discoverability
This will give the following output when run from inside common:
$ make help
help             This help message
argosecret       creates the argo secret
show             show the starting template without installing it
test             run helm tests
helmlint         run helm lint
validate-origin  verify the git origin is available
deploy           deploys the pattern
upgrade          runs helm upgrade
uninstall        runs helm uninstall
vault-init       inits, unseals and configured the vault
vault-unseal     unseals the vault
load-secrets     loads the secrets into the vault
Tested on Linux (bash+zsh) and on Mac OSX (bash+zsh)

Add a make help target to list all existing targets (common)

---

Makefile

Currently we hard-code origin as the remote to use for git.
Allow the user to override this via TARGET_ORIGIN variable (which
defaults to 'origin' like before)
Tested with:
make upgrade
make TARGET_ORIGIN=fork upgrade
And the commands used the 'origin' remote and the 'fork' one
respectively.
Reason for this is that I hate calling my forks 'origin' and I rarely
even have an 'origin' remote. I call my remotes 'fork' so I do not push
branches upstream accidentally.

Allow overriding the remote name

---

.github/workflows/linter.yml
Makefile

Note that this depends on the generated static files that
we push out into our ocp-schemas repo.
Example CI run:
stdin - PlacementBinding edge-placement-binding is valid
stdin - PlacementBinding openshift-gitops-placement-binding is valid
stdin - PlacementRule edge-placement is valid
stdin - PlacementRule openshift-gitops-placement is valid
stdin - MultiClusterHub multiclusterhub is valid
stdin - Policy openshift-gitops-policy is valid
stdin - Policy edge-clustergroup-policy is valid
stdin - ConfigMap environment is valid
stdin - clustersecretstores.external-secrets.io CustomResourceDefinition skipped
stdin - externalsecrets.external-secrets.io CustomResourceDefinition skipped
stdin - secretstores.external-secrets.io CustomResourceDefinition skipped
stdin - ClusterRole …

Move to kubeconform

---

clustergroup/values.yaml

In multicloud-gitops via e5c6fb68 (Remove some obsolete options and add
needed settings for isHubCluster) it was missed to backport the common
hunk to the common/ proper tree.
Fix this so proper common/ and multicloud-gitops/common/ do not differ
at all.

Bring in some change that was missed

---

Makefile

Of course openapi2json is broken with Tekton Pipelines and Tasks, so we
need to be able to skip resources on a per-project basis.

Allow skipped resource types to be customized

---

scripts/vault-utils.sh

Leave only the read one for the time being as it seems to be a saner
default. If more granularity is needed customizations are qreuired in
any case.
Tested and I can still correctly access the secret on the config-demo
app on the regional cluster.

Tighten vault hub policy a bit

---

scripts/ansible-push-vault-secrets.sh
scripts/vault-utils.sh

- Make sure we only bail out when both KUBECONFIG and ~/.kube/config are not set
- Stop bailing out if the vault file exists

Fix wrong KUBECONFIG fail logic and do not bail out if vault init output already exists

---

Makefile
install/templates/argocd/namespace.yaml
install/templates/argocd/subscription.yaml
install/values.yaml

It used to be for deploying multiple patterns. Let's drop it for the
time being: Nowhere do we document how and when to use it anyways.

Remove the bootstrap concept from common/

---

scripts/ansible-push-vault-secrets.sh

The format we expect is:
secrets:
group1:
secret1: value1
secret2: value2
group2:
secret1: value1
This will generate the following vault injections:
vault kv put secret/hub/group1 -> secret1=value1 secret2=value2
vault kv put secret/hub/group2 -> secret1=value1
Now if the file has a format that we do not really recognize, for
example like:
secrets:
foo: bar
group1:
secret1: value1
We will error out as follows:
TASK [Check if any of the passwords has only s3.[accessKey,secretKey] and generate the combined s3Secret in that case]
fatal: [localhost]: FAILED! => {"msg": "The conditional check
'\"s3.accessKey\" in item.value.keys()' failed. The error was: error
while evaluating conditional (\"s3.accessKey\" in
item.value.keys()): 'ansible.utils.unsafe_proxy.AnsibleUnsafeText
object' has no …

Improve error message when values-secret.yaml is not formatted as expected

---

clustergroup/templates/argocd-super-role.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml

Since gitops 1.5.0 the secondary argocd instance's web interface is
erroring out with:
Failed to query provider "https://hub-gitops-server-multicloud-gitops-hub.apps.bandini-dc.blueprints.rhecoeng.com/api/dex":
Get "http://hub-gitops-dex-server.multicloud-gitops-hub.svc.cluster.local:5556/api/dex/.well-known/openid-configuration":
dial tcp 172.30.229.125:5556: connect: connection refused
The exact problem is:
W0421 07:32:56.239809       1 reflector.go:324]
pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167:
failed to list *v1.Secret: secrets is forbidden: User
"system:serviceaccount:multicloud-gitops-hub:hub-gitops-argocd-dex-server"
cannot list resource "secrets" in API group "" in the namespace
"multicloud-gitops-hub" E0421 07:32:56.239838       1
reflector.go:138] …

ServiceAccount hub-gitops-argocd-dex-server needs more permissions

---

examples/values-secret.yaml

Ilkka mentioned this and it's quite annoying as load-secret will
barf due to the wrong line.
This is just a quick removal to avoid having people hit this issue.
Maybe we should just drop this entirely and have only custom top-level
values-secret.yaml.template files like we do in multicloud-gitops.

Remove wrong line in examples/values-secret.yaml

---

scripts/ansible-push-vault-secrets.sh

Currently we break horribly when a user adds a multiline secret in yaml
(via the | operator):
failed: [localhost] (item=cert-test) => {"ansible_loop_var": "item",
"changed": true, "item": {"key": "cert-test", "value": {"ca.crt":
"-----BEGIN CERTIFICATE-----\nMIIEgjCCA
uqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAzMREwDwYDVQQKDAhDT09M\nLkxBQjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTIyMDEwNTEz\nfoo\nbar\nbaz\n"}},
"rc": 127, "return_code": 127, "stderr": "Failed to parse K=V data:
invalid key/value pair \"CERTIFICATE-----\": format must be
key=value\nsh: line 1:
MIIEgjCCAuqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAzMREwDwYDVQ QKDAhDT09M:
command not found\nsh: line 2:
LkxBQjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTIyMDEwNTEz:
command not found
Let's try to escape key and value and let the yaml …

WIP Quote key and value when uploading a secret

---

acm/templates/policies/application-policies.yaml
acm/templates/policies/ocp-gitops-policy.yaml
tests/acm-naked.expected.yaml
tests/acm-normal.expected.yaml

The namespaceSelector example:
namespaceSelector:
include: ["default"]
exclude: ["kube-*"]
shows up in many places in the documentation. Yet it is not particularly
relevant. Full explanation can be found in
https://bugzilla.redhat.com/show_bug.cgi?id=2079393
Let's just drop the exclude, since we already define an include
without a regex, there is no point in excluding anything really.
Tested by redeploying a full multicloud-gitops pattern across
two clusters.

Remove useless exclude: kube-* from ACM policies

---

scripts/ansible-push-vault-secrets.sh

As noted by Johnny 'ansible-galaxy collection install community.kubernetes'
does not care about lower-level dependencies whatsoever, so let's check
if the python modules is importable first as the error otherwise is
quite non-obvious.

Add a small precheck to make sure python kubernetes is importable

---

acm/templates/policies/application-policies.yaml
acm/templates/policies/ocp-gitops-policy.yaml
tests/acm-naked.expected.yaml
tests/acm-normal.expected.yaml

The error with ACM 2.5 is the following:
Failed to create policy template
ConfigurationPolicy.policy.open-cluster-management.io
"config-demo-secret" is invalid: spec.severity: Unsupported value:
"med": supported values: "low", "Low", "medium", "Medium", "high",
"High", "critical", "Critical"
Use "medium" as severity. Tested with ACM 2.5 and the policies come up
correctly.

Change all ACM policies' severity definition

---

scripts/ansible-push-vault-secrets.sh
scripts/vault-utils.sh

1) Sometimes vault namespace does not show up for query when ansible-push-vault-secrets is running. This adds retry logic to give it a few tries before erroring out.
2) Move the rename of the pattern-vault.init (password file) until after the first check for vault readiness. This enables us to run make vault-init idempotently (that is - make vault-init will exit successfully if there's a currently running and correctly configured vault)

Improve installation resilience for vault

---

Makefile
clustergroup/templates/imperative/clusterrole.yaml
clustergroup/templates/imperative/configmap.yaml
clustergroup/templates/imperative/job.yaml
clustergroup/templates/imperative/namespace.yaml
clustergroup/templates/imperative/rbac.yaml
clustergroup/templates/imperative/role.yaml
clustergroup/templates/imperative/serviceaccount.yaml
clustergroup/values.yaml
tests/clustergroup-normal.expected.yaml

This creates a CronJob (by default runs every 10mins) which will run
all the playbooks listed in imperativeJobs: in a values-*.yaml file.
The jobs will be run sequentially and need to be idempotent.
They are currently using a rhel9-ubi container with ansible and some
additional tools in them.

Add initial support for imperative jobs

---

Makefile

We're using vault + the load-secrets target to inject secrets in it.
Let's not pass the secret values via helm anywhere as this really
defeats the whole purpose of uploading the secrets out of band.

Remove SECRETS from the initial helm chart args passing

---

clustergroup/templates/imperative/job.yaml

If a job was the "disabled: true" key in its definition
it won't be rendered in the CronJob definition.
The use case here is to be able to simply noop some jobs
without having to remove them fully.
Tested with:
imperative:
jobs:
- name: foo
playbook: ansible/playbooks/foo.yml
- name: bar
playbook: ansible/playbooks/bar.yml
disabled: true
- name: baz
playbook: ansible/playbooks/baz.yml
disabled: false
The above generates the following initContainers in the
CronJob definition (note how bar is skipped):
initContainers:
...
- name: foo
image: registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest
command:
...
- ansible/playbooks/foo.yml
- name: baz
command:
...
- ansible/playbooks/test.yml

Add support for .disabled in imperative jobs

---

install/crds/applications.argoproj.io.yaml

This adds a bunch of new parameters like:
ignoreMissingValueFiles
passCredentials
skipCrds
forceCommonAnnotations
forceCommonLabels
Note that if helm install fails with:
"Error: INSTALLATION FAILED: unable to build kubernetes objects from
release manifest: error validating \"\": error validating data:
ValidationError(Application.spec.source.helm): unknown field
\"ignoreMissingValueFiles\" in io.argoproj.v1alpha1.Application.spec.source.helm
It's likely that the cluster has an old crd and it needs to be replaced
with this one (delete the old one)

Update argo crd

---

ansible/roles/vault_utils/tasks/push_secrets.yaml

If a user chooses to unseal the vault from inside the cluster
(i.e. without make vault-init) make load-secrets will probably
fail because the cronjob to unseal the vault will not have
run by the time we try to inject the secrets into the vault.
Since ansible has no mechanism to retry/until over an include_task,
we just add a vault_status exec call that loops a few times until
sealed turns false.
Tested this with unsealing done from within the cluster via a cronjob
and via make vault-init.

In push_secrets wait more if the vault is unsealed

---

acm/templates/policies/application-policies.yaml
clustergroup/templates/applications.yaml
install/templates/argocd/application.yaml
tests/acm-normal.expected.yaml
tests/clustergroup-normal.expected.yaml
tests/install-naked.expected.yaml
tests/install-normal.expected.yaml

This will allow us to always add values files that do not exist,
like per-cluster overrides and so on.
Tested on a multicloud-gitops deployment successfully

Add ignoreMissingValueFiles: true on helm charts

---

Makefile
ansible/roles/vault_utils/tasks/push_secrets.yaml
clustergroup/templates/imperative/_helpers.tpl
clustergroup/templates/imperative/job.yaml
clustergroup/templates/imperative/unsealjob.yaml
clustergroup/values.yaml
tests/clustergroup-normal.expected.yaml

This commit adds support for a separate unsealJob CronJob template which is
enabled when when a user sets clusterGroup.unsealVaultInsideCluster to
true and the template is applied to the hub. This makes it so that the
cluster is unsealed directly via cronjob and the vault unseal keys are
stored inside a secret in OCP. Note that this is provided for
convenience only and it is not recommended to store vault's unseal keys
and root login token inside a kubernetes cluster.
Two different design choices were explored and tried:
A) Via some global switch + an additional unseal template (which is what
this review is all about)
If "clusterGroup.unsealVaultInsideCluster" is true we render an additional template
in common/clustergroup/templates/imperative/unsealjob.yaml which then kicks off
the …

Add job to unseal the vault from the cluster

---

acm/templates/policies/application-policies.yaml
clustergroup/templates/applications.yaml
install/templates/argocd/application.yaml
tests/acm-normal.expected.yaml
tests/clustergroup-normal.expected.yaml
tests/install-naked.expected.yaml
tests/install-normal.expected.yaml

As suggested by @beekhof via
https://github.com/hybrid-cloud-patterns/industrial-edge/pull/123/ we
add foreground finalizers for all of our argo applications. While we're
at it we replace acm's application policy finalizer from
"argoproj.io/finalizer" to the same foreground one we use in the other
applications: "resources-finalizer.argocd.argoproj.io/foreground"
This should improve our uninstall story in general.

Add finalizers to all applications

---

Makefile

We now added the Pattern API to ocp-schemas, so we can check for it

Remove Pattern from kubeconform skiplist

---

Makefile
acm/templates/policies/application-policies.yaml
acm/values.yaml
clustergroup/templates/applications.yaml
clustergroup/templates/argocd.yaml
clustergroup/values.yaml
install/templates/argocd/application.yaml
install/values.yaml
tests/acm-normal.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml
tests/install-naked.expected.yaml
tests/install-normal.expected.yaml

valuesDirectoryURL was only needed when argo did not support referencing
the values files inside the pattern's git repo root [1]. I.e. any value
file that starts with '/' is assumed to reference the git repo's root.
The main reason we do this, is because argo tends to cache values files
over http and ignore refresh requests (needs a hard-refresh), so the
expectation of doing gitops and values files over http breaks down
somewhat. [2]
We have three possible options to fix this:
1. We ignore the issue [2] entirely. We keep things as is and we revert
the operator change [3]. I.e. we always fetch the values files from
URL (this keeps things as is and we unbreak IE when deployed via the
operator), but we are more susceptible to the gitops values caching
issue. We could reevaluate this once …

Drop valuesDirectoryURL entirely

---

operator-install/templates/namespace.yaml
operator-install/templates/operator_group.yaml
operator-install/templates/pattern.yaml
operator-install/templates/subscription.yaml
operator-install/values.yaml
tests/operator-install-naked.expected.yaml
tests/operator-install-normal.expected.yaml

The UI installs it by default in the patterns-operator-system namespace.
Let's have UI and make operator-install in sync on this.

Move operator installation in patterns-operator-system namespace

---

clustergroup/templates/subscriptions.yaml

While testing deploying Industrial Edge on a FIPS mode the AMQ Streams operator was not deploying due to the FIPS mode.  There was a need to pass an environment variable to the operator so the way we do that is by defining the ENV in the manifest.
This PR partly implements the .spec.config.env found in the [4.10 Subscription Spec](https://docs.openshift.com/container-platform/4.10/rest_api/operatorhub_apis/subscription-operators-coreos-com-v1alpha1.html).  It only implements the .spec.config.env[].name and .spec.config.env[].value and does not implement the .spec.config.env[].valueFrom.
A subscription in our values files can add environment variables in the subscription definition which will get passed to the subscription operator:
``` amqstreams-dev:
name: amq-streams
namespaces:
- …
```

Adding support for .spec.config.env to subscription.yaml template

---

.ansible-lint
ansible/roles/vault_utils/tasks/push_secrets.yaml

This extends values-secret.yaml parsing to allow entries of the form:
```
files:
key: <filename>
```
Which requires that <filename> exist and be a valid file.
This will add secrets of the form:
secrets/<path>/key file=<file content>
This works by cat'ing the file into a pipe with oc exec.

WIP: Extend values-secret parsing to include files section

---

ansible/roles/vault_utils/defaults/main.yml
ansible/roles/vault_utils/tasks/vault_secrets_init.yaml
golang-external-secrets/templates/golang-external-secrets-hub-clusterrolebinding.yaml
golang-external-secrets/templates/golang-external-secrets-hub-secretstore.yaml
tests/golang-external-secrets-naked.expected.yaml
tests/golang-external-secrets-normal.expected.yaml

In kubernetes 1.24 (OCP 4.11) the token for service account does not get
created anymore [1]. In order to support all of our supported OCP versions
with the least effort, we just create a secret and associate it to the
golang-external-secret service account.
While we're at it we simplify the ansible a code a bit and simply always
rely on having the golang-external-secrets secret created by default.
Tested on OCP 4.8, 4.9, 4.10 and 4.11. In all tests I saw the
config-demo-secret being created inside the cluster and 'make install'
succeeded correctly.
Closes: https://issues.redhat.com/browse/MBP-321
[1] https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#deprecation=

Support k8s 1.24

---

Makefile

This way in the patterns we can just rely on the common target and
disable additional linters via the DISABLE_LINTERS variable.

Add a DISABLE_LINTERS variable to super-linter target

---

ansible/roles/vault_utils/tasks/vault_delete.yaml
ansible/roles/vault_utils/tasks/vault_secrets_init.yaml
ansible/roles/vault_utils/tasks/vault_status.yaml
ansible/roles/vault_utils/tasks/vault_unseal.yaml

Detect if vault deployments has more pods and assume `vault-0` as the leader.
Make the other `vault-x` join the raft cluster as followers and finally unseal the followers.
Additionally: Added check for missing serviceAccount token secret

Allow ha vault deployments

---

ansible/roles/vault_utils/tasks/vault_status.yaml

Otherwise we get the printout of all the metadata returned by the pod
list call. Tested on an MCG cluster.

Silence Get Pods loop a bit

---

ansible/roles/vault_utils/tasks/vault_status.yaml

This will make things a bit simpler to debug as the index is not very
interesting. Also remove the extended loop as it just uses up memory
needlessly

Print the name of the pod when getting pods

---

clustergroup/templates/imperative/clusterrole.yaml
clustergroup/templates/imperative/configmap.yaml
clustergroup/templates/imperative/job.yaml
clustergroup/templates/imperative/namespace.yaml
clustergroup/templates/imperative/rbac.yaml
clustergroup/templates/imperative/role.yaml
clustergroup/templates/imperative/serviceaccount.yaml

The change in structure is needed because there are two things that require the creation of the imperative role/clusterrole/namespace/rbac:
1) A request for an imperative job
2) A request for the insecure vault unseal operation
These may occur together or separately; an unseal without a job in the old scheme would fail because the role/namespace etc was not created for it

Change conditionals on imperative framework

---

ansible/roles/vault_utils/tasks/push_secrets.yaml

Users may want to specify their "file" secrets using ~, which causes confusing behavior in Ansible, since ansible stat calls the expanduser filter on its path (causing the lookup of such a file to succeed), but then we call `cat` on it when loading it (in single quotes) which does not have that behavior.
This change normalizes the behaviors between the different sections of the task.

Call expanduser on file to match stat behavior

---

clustergroup/templates/applications.yaml

This effectively deprecates the variable global.options.syncPolicy but this is the only place we were using it, and we weren't checking syncPolicy here either. This standardizes usage without changing behavior.

Standardize sync-policy handling 

---

acm/templates/provision/clusterpool.yaml
tests/acm-normal.expected.yaml

Otherwise we end up with the following error whenever we have
managedClusters that do not have clusterpools defined in them:
cluster.open-cluster-management.io/v1beta1/ManagedClusterSet open-cluster-management region-one SyncFailed the server could not find the requested resource

Only create managedclustersets if there are clusterpools

---

Makefile

After removing the subscription, the CSV is not deleted and this might cause problems in further installations or look confusing in the Openshift console.

Remove CSV after uninstalling

---

Makefile

Let's not call oc too many times for every invocation.
Moving the CSV variable definition inside the uninstall avoids that.

Move CSV definition into the uninstall target

---

operator-install/templates/pattern.yaml
operator-install/values.yaml
tests/operator-install-naked.expected.yaml
tests/operator-install-normal.expected.yaml

Add support for mapping .Values.main.gitops.channel for operator installs. Default to "stable".

Add operatorchannel parameter

---

clustergroup/templates/applications.yaml
clustergroup/templates/cluster-external-secrets.yaml
clustergroup/values.yaml
examples/values-example.yaml
examples/values-secret.yaml
tests/clustergroup-normal.expected.yaml

This is a suggested feature that I decided to use for registering new clusters in ArgoCD instead of using ACM.
By creating ExternalSecrets with a specific label in them, ArgoCD can add them to its configuration. This reduces the technical footprint for cases in which ACM is not necessary.
Check the parameters that are now part of the default configuration.

Allow configuring clusters with ExternalSecrets

---

Makefile

This does it in common/ so we can simplify pattern's makefiles
We have ansible-lint that covers things linting-wise.

Disable ansible linting in the super-linter

---

clustergroup/templates/subscriptions.yaml
tests/clustergroup-normal.expected.yaml

Currently a user can only get the global.options.useCSV to true
(defaults to false) and once it is set to true *all* subscrptions
will get their 'startingCSV' fields populated with whatever is set in
the 'csv' subscription field. So all subscriptions *must* have a csv
field set.
With this change we can add a per-subscription useCSV toggle which
allows us to do this case by case.
A use-case here is to pass something like the following:
subscriptions:
amqstreams-dev:
name: amq-streams
namespace: manufacturing-dev
channel: amq-streams-1.8.x
csv: amqstreams.v1.8.0
installPlanApproval: Manual
The above will make sure the startingCSV is amqstreams.v1.8.0 *only* for
the amq-streams operator, and it will make the installation manual.
So once the manual installation is approved we get v1.8.0 …

Implement a per-subscription csv field

---

clustergroup/templates/subscriptions.yaml

We added a feature, a while ago, to allow the user to disable the subscription if desired. Adding
the *disable: true* key/value pair to the definition of the subscription would skip the generation
of the subscription manifest.
There are two ways to describe subscriptions in our values-*.yaml file.
The first way is to define a subscription to be targeted to one namespace:
seldon-dev:
name: seldon-operator
namespace: manuela-tst-all
source: community-operators
csv: seldon-operator.v1.12.0
The second way of define a subscription is to target multiple namespaces.  This means that
the subcription will get applied to each namespace listed:
seldon:
disabled: true
name: seldon-operator
namespaces:
- manuela-ml-workspace
- manuela-tst-all
source: community-operators
csv: seldon-operator.v1.12.0 …

Update for subscription.yaml template in common/clustergroup

---

scripts/pattern-util.sh

- Explicitely ignore ssh pubkeyacceptedalgorithms config option
- Bind mount the ssh-agent socket if it is set

Fix wrapper corner cases

---

scripts/pattern-util.sh

And replace it with an echo + pwd combo that works both on Linux
and on Mac OSX.
Note that at this point the Mac OSX support is still not working
with ssh auth due to podman not being able to bind mount host dirs into
the container on the podman machine vm (or at least not /private/tmp)
Tested on both Fedora and Mac OSX

Drop readlink -f usage

---

Makefile
tests/clustergroup-normal.expected.yaml
tests/clustergroup.expected.diff

We should *never* ever pass values-secrets.yaml to helm. As that file is
injected to vault out-of-band and has nothing to do with helm at all.

Drop -f example/values-secrets.yaml from make test

---

scripts/pattern-util.sh

It breaks on Silverblue with:
./common/scripts/pattern-util.sh make push-secrets                                                                                                          ─╯
Error: unknown shorthand flag: 'o' in -o
See 'podman run --help'

Drop GIT_SSH_COMMAND from the wrapper

---

ansible/plugins/modules/vault_load_secrets.py
ansible/tests/unit/test_vault_load_secrets.py
ansible/tests/unit/values-secret-broken1.yaml
ansible/tests/unit/values-secret-broken2.yaml
ansible/tests/unit/values-secret-empty-files.yaml
ansible/tests/unit/values-secret-empty-secrets.yaml

- Return {} when parsing an empty yaml file
- Make sure to skip loops that have None in their range
- Make sure to expand user path when checking for file existence
- Add a number of testcases that cover corner cases in the values files
- Fix up flake8 and black warnings

Fix #184 (empty files: key)

---

ansible/plugins/modules/vault_load_secrets.py
ansible/tests/unit/test_vault_load_secrets.py
ansible/tests/unit/values-secret-broken3.yaml

- Cleanup tests and bail out properly when files/secrets: are lists
- Reformat isinstance list fail message

Additional unittests and another yaml cornercase

---

ansible/plugins/modules/vault_load_secrets.py
ansible/roles/vault_utils/tasks/push_secrets.yaml
ansible/tests/unit/mcg-values-secret.yaml
ansible/tests/unit/template-mcg-missing.yaml
ansible/tests/unit/template-mcg-working.yaml
ansible/tests/unit/test_vault_load_secrets.py
scripts/vault-utils.sh

- Add a pattern_dir variable to the playbook
- Add a check a check_missing_secrets parameter to vault_load_secrets
- Add a number of unit tests to verify the new check_missing_secrets functionality
- Add all the code to actually verify secrets against values-secret-template.yaml but keep it disabled
- Fix a couple of linting issues

verify local secret template

---

scripts/pattern-util.sh

Newer ssh versions (worked for me in F36, broke in F37) seem to dislike
if the ssh-agent socket is in /ssh-agent in the container. The ssh-agent
on will just refuse the connections from the container.
Let's bind the original host path in the same place in the container.
That way we can also drop the real_path function().
Tested and now ssh agent correctly works again.

Tweak the SSH paths so ssh-agent works again

---

scripts/pattern-util.sh

Without this patch the wrapper breaks when KUBECONFIG is unset
and ~/.kube/config exists.
We must pass -e KUBECONFIG *only* if it is set, otherwise we end up
passing KUBECONFIG="" which then will confuse ansible.
Tested and now 'make load-secrets' works correctly via the wrapper
whenever KUBECONFIG is unset and ~/.kube/config exists.

Pass -e KUBECONFIG *only* if it is set

---

Makefile

Spotted by Jonny.
Before:
~/test me/multicloud-gitops -> NAME=$(shell basename "`pwd`") -> "test"
After:
~/test me/multicloud-gitops -> NAME=$(shell basename "`pwd`") -> "multicloud-gitops"

Get the correct pattern name when the path has a folder

---

Changes.md
Makefile
acm/templates/policies/application-policies.yaml
clustergroup/templates/plumbing/applications.yaml
install/templates/argocd/application.yaml
tests/acm-normal.expected.yaml
tests/acm.expected.diff
tests/clustergroup-normal.expected.yaml
tests/clustergroup.expected.diff
tests/install-naked.expected.yaml
tests/install-normal.expected.yaml
tests/install.expected.diff

We add global.clusterVersion variable (OCP major.minor) and pass it on.
Then we add a /values-<global.clusterVersion.yaml> in the helm parameter
list.
This will allow us to have per-ocp version overrides and potentially
avoid having to use git branches more than needed.
Tested on MCG (w/ACM) and observed the correct global.clusterVersion
on both argo instances on hub and spoke. Also the new values includes
looked correct.

Implement global.clusterVersion

---

ansible/plugins/modules/vault_load_secrets.py
ansible/tests/unit/test_vault_load_secrets.py

Lester reported one issue with the following backtrace:
TASK [vault_utils : Loads secrets file into the vault of a cluster]
***********************************************************************
An exception occurred during task execution. To see the full
traceback, use -vvv. The error was: subprocess.CalledProcessError:
Command 'oc exec -n vault vault-0 -i -- sh -c "vault kv put
'secret/hub/aws'
s3Secret='...'"'
returned non-zero exit status 1. fatal: [localhost]: FAILED! =>
{"changed": false, "module_stderr": "Traceback (most recent call
last):\n  File
\"/home/claudiol/.ansible/tmp/ansible-tmp-1666041131.290091-69234-174948554391046/AnsiballZ_vault_load_secrets.py\",
line 107, in <module>\n    _ansiballz_main()\n  File
\"/home/claudiol/.ansible/tmp/ansible-tmp-1666041131.290091-69234-17 …

Add possibility to retry commands in run_command()

---

.gitleaks.toml

This way splunk that runs on our repos won't barf on the
example secrets in our unit tests.
Use a symlink so we maintain a single copy of that file.

Symlink .github/linters/.gitleaks.toml to .gitleaks.toml

---

golang-external-secrets/README.md
golang-external-secrets/values.yaml
tests/golang-external-secrets-naked.expected.yaml
tests/golang-external-secrets-normal.expected.yaml

Thsi changes switches to use UBI based images as reccomended by
Matthias.
Tested on MCG on hub and also checked the regional cluster is still
working correctly:
oc get -n golang-external-secrets pods -o yaml |grep -i image:
image: ghcr.io/external-secrets/external-secrets:v0.6.0-ubi
image: ghcr.io/external-secrets/external-secrets:v0.6.0-ubi
image: ghcr.io/external-secrets/external-secrets:v0.6.0-ubi
image: ghcr.io/external-secrets/external-secrets:v0.6.0-ubi
image: ghcr.io/external-secrets/external-secrets:v0.6.0-ubi
image: ghcr.io/external-secrets/external-secrets:v0.6.0-ubi
Note that after this change, when we update the ESO subchart we also
need to tweak the version. That is why I added a README with the
reminder.

Use UBI based images for ESO

---

ansible/roles/vault_utils/tasks/push_secrets.yaml
ansible/roles/vault_utils/tasks/vault_init.yaml
ansible/roles/vault_utils/tasks/vault_secrets_init.yaml

Let's lower the risk of leaking any secrets by adding no_log: true to
any task that might be managing secrets/tokens or the likes.
Tested via MCG and correctly deployed it.

Use no_log: true in any sensitive place

---

Makefile

By adding the following:
-e VALIDATE_DOCKERFILE_HADOLINT=false \
-e VALIDATE_TEKTON=false \
we can drop the custom super-linter target in most patterns. If there is
a pattern that needs to enable those it can update the super-linter
target in its top-level Makefile.
Also remove the .mypy_cache folder as it gets generated by super-linter
and then ends up being scanned as well which is inefficient.

Disable VALIDATE_DOCKERFILE_HADOLINT VALIDATE_TEKTON by default in common/Makefile

---

ansible/plugins/modules/vault_load_secrets.py
ansible/tests/unit/test_vault_load_secrets.py
ansible/tests/unit/values-secret-fqdn.yaml

If we have a values-secrets.yaml like the following:
secrets.region-one.blueprints.rhecoeng.com:
foo:
secret1: bar
This currently breaks as we split all dots. Only split the first dot
after secrets. So this example can work.
Also add a test case to cover for this.

Make sure we can parse FQDNs after a secrets tag in values-secrets.yaml

---

ansible/ansible.cfg

The profile_roles and profile_tasks callbacks provide timinng
information for tasks and roles to execute.

Added callbacks to ansible.cfg

---

Changes.md
acm/templates/policies/application-policies.yaml
clustergroup/templates/plumbing/applications.yaml
tests/acm-normal.expected.yaml
tests/acm.expected.diff
tests/clustergroup-normal.expected.yaml
tests/clustergroup.expected.diff

In the same vein as /values-<ocpversion>-<clustergroup>.yaml support, we
allow for clusterplatform overrides. Values files now look like the
following:
/values-global.yaml, /values-group-one.yaml, /values-AWS-group-one.yaml, /values-4.11-group-one.yaml
Tested with
https://github.com/hybrid-cloud-patterns/patterns-operator/pull/42 and
could get the correct /values file inclusion in cluster-wide argo and on
the namespaced-argo on both the hub and the spoke clusters.

Add support for /values-<platform>-<clustergroup>.yaml

---

ansible/ansible.cfg

It brings little to the table and is making the output quite confusing
for users. It's also not really too relevant with our fairly short-lived
tasks.

Drop callbacks_enabled

---

ansible/roles/vault_utils/tasks/push_secrets.yaml

This is triggered only when the file is detected to be encrypted.
It makes for a better UX as the prompt makes it clear for which
file we're asking the password.

Prompt ansible-vault password via ansible.builtin.pause

---

ansible/roles/vault_utils/tasks/push_secrets.yaml

Tested with:
1. VALUES_SECRET=~/values-secret.yaml.v2 make load-secrets
TASK [vault_utils : Set values-secret yaml file to /home/michele/values-secret.yaml.v2] ***
2. make load-secrets
TASK [vault_utils : Find first existing values-secret yaml file] **
Both worked correctly

Allow picking a custom values-secret.yaml file via the VALUES_SECRET env var

---

ansible/ansible.cfg

While it is not needed just yet, we are likely to need a filter plugin
sooner rather than later, so best if we just prepare the path for it in
common.

Add filter_plugins path in common

---

ansible/roles/vault_utils/values-secrets.v2.schema.json

This allows us to use if..then..else statements:
https://json-schema.org/understanding-json-schema/reference/conditionals.html
Now we can require one of 'path' or 'value' attributes whenever
'onMissingValue' is set to 'prompt'.
Also when 'onMissingValue is 'generate' we can require 'vaultPolicy'
Note that the ifs need to be wrapped inside an allOf in order to not
be ignored by the JSON parser (due to multiple keys being the same:
'if', 'then')

Move to draft-07 of the json schema for V2

---

ansible/plugins/module_utils/load_secrets_v2.py
ansible/tests/unit/test_vault_load_secrets_v2.py

By default _run_command uses check_rc=True. In the secret existence
case, we need to set it to False in order to not raise an exception
when the secret is missing.
Otherwise we'll get the following error:
TASK [vault_utils : Loads secrets file into the vault of a cluster]
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "oc exec -n
vault vault-0 -i -- sh -c 'vault kv get -mount=secret -field=secret
hub/config-demo'", "msg": "No value found at
secret/data/hub/config-demo\ncommand terminated with exit code 2", "rc":
2, "stderr": "No value found at secret/data/hub/config-demo\ncommand
terminated with exit cod e 2\n", "stderr_lines": ["No value found at
secret/data/hub/config-demo", "command terminated with exit code 2"],
"stdout": "", "stdout_lines": []}

Do not raise exception if secret's existence check fails

---

clustergroup/templates/core/subscriptions.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-normal.expected.yaml

Each subscription seems to have a default version, so inserting our own default could get in the way of that. This PR only sets a channel if user requests one.

Remove stable default from channels

---

ansible/plugins/module_utils/load_secrets_v2.py
ansible/tests/unit/test_vault_load_secrets_v2.py

The 'counter' variable is used to detect if it is the first vault kv
command to be run (i.e. vault kv put as opposed to vault kv patch for
subsequent runs), so we need to reset it for every top-level secret.
We introduce an additional variable to count every secret entry
uploaded.

Split secret counter in two variables

---

Changes.md
Makefile
ansible/roles/vault_utils/README.md
ansible/roles/vault_utils/defaults/main.yml
ansible/roles/vault_utils/tasks/vault_init.yaml
ansible/roles/vault_utils/tasks/vault_unseal.yaml
clustergroup/templates/imperative/clusterrole.yaml
clustergroup/templates/imperative/configmap.yaml
clustergroup/templates/imperative/namespace.yaml
clustergroup/templates/imperative/rbac.yaml
clustergroup/templates/imperative/role.yaml
clustergroup/templates/imperative/serviceaccount.yaml
clustergroup/templates/imperative/unsealjob.yaml
clustergroup/test.yaml
clustergroup/values.yaml
examples/industrial-edge-hub.yaml
examples/medical-diagnosis-hub.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml
tests/clustergroup.expected.diff

We always just unseal the vault from the cluster. We simply drop support
of running these commands manually entirely. The advantage is that the
code is a lot simpler and we have a single avenue to do things.
Tested as following:
1. Deployed MCG and observed loading of secrets happening correctly
2. Removed the imperative/vaultkeys secret
3. Deleted the vault-0 pod
4. Observed that the vault-0 pod was restarted and that the vault was
sealed
5. Observed that the unsealvault cronjob did nothing
6. Restored the vaultkeys secret
7. Observed that the unsealvault cronjob unsealed the vault correctly
again

Drop insecureUnsealVaultInsideCluster

---

Makefile
ansible/roles/vault_utils/README.md
ansible/roles/vault_utils/defaults/main.yml
scripts/vault-utils.sh

This was only used when we had support for storing the unseal keys in
files. Since we dropped this support we can remove any traces of that.

Drop any remains of output_file

---

ansible/plugins/filter/parse_acm_secrets.py

This filter takes a bunch of acm secrets that represent the remote clusters
(Usually it is all secrets that are labeled with:
"apps.open-cluster-management.io/secret-type=acm-cluster")
These secrets are usually in the form of:
data:
config: ewogIC...
name: bWNnLW9uZQ==
server: aHR0cHM6Ly9hcGkubWNnLW9uZS5ibHVlcHJpbnRzLnJoZWNvZW5nLmNvbTo2NDQz
The filter parses the secret (name, server, config) and returns a dictionary of secrets in the
following form:
<acm-name>:
name: <acm-name>
cluster_fqdn: <fqdn-without-api-prefix>
server_api: https://api.<cluster_fqdn>:6443
bearerToken: <bearerToken to access remote cluster>
tlsClientConfig: <tlsClientConfig in ACM config field>
...

Add filter to parse ACM secrets

---

ansible/roles/vault_utils/tasks/vault_unseal.yaml

All other tasks are run only when the vault is sealed, so no point in
skipping this one

Only set vaultkeys fact when the vault is sealed

---

ansible/plugins/module_utils/load_secrets_v2.py
ansible/tests/unit/test_vault_load_secrets_v2.py

We fix two things here:
1) There was a missing @ when uploading a file into the vault, so we'd
get the /tmp/vcontent path instead of the actual content
2) There was a bug with paths not expanding the ~ when uploading in v2
Tested and now things work correctly

Fix two V2 secret format corner-case bugs

---

acm/templates/provision/clusterpool.yaml
tests/acm-normal.expected.yaml

On a deploy using clusterPools the acm app will stay in error forever.
The reason for this is that the CRDs for the above objects won't exist
until the MultiClusterHub is installed. So Argo CD won't find the CRD
in the sync and will fail with the error the server could not find the
requested resource.
Add the "argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true" on those resources, just like we do for Policies.
Co-Authored-By: Lester Claudio <claudiol@redhat.com>

Add SkipDryRunOnMissingResource=true on ClusterPools, ClusterClaims and ManagedClusterSets

---

ansible/plugins/module_utils/load_secrets_v2.py
ansible/tests/unit/test_vault_load_secrets_v2.py

Files with 'base64: true' are not being base64-encoded correctly.
Let's make sure the base64 encoding happens before we use /tmp/vcontent
to upload the file to the vault.

Fix base64 file upload

---

clustergroup/values.schema.json

We're only in charge of global, main, secretstore and clustergroup.
What happens in the other parts othe values file is not our job to
validate.

Set additionalProperties to true for top-level objects

---

clustergroup/values.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-naked.expected.yaml

Before this change:
$ helm template common/clustergroup --name-template multicloud-gitops  -f ~/Engineering/cloud-patterns/multicloud-gitops/values-hub.yaml >/dev/null
coalesce.go:223: warning: destination for pattern-clustergroup.clusterGroup.managedClusterGroups is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for pattern-clustergroup.clusterGroup.subscriptions is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for pattern-clustergroup.clusterGroup.applications is a table. Ignoring non-table value ([])
After this change:
$ helm template common/clustergroup --name-template multicloud-gitops  -f ~/Engineering/cloud-patterns/multicloud-gitops/values-hub.yaml >/dev/null
$

Fix some validation schema warnings

---

Changes.md
Makefile

This checks all the values file singularly and together with
./values-global.yaml against common/clustergroup schema.
Working example:
$ make validate-schema
make -f common/Makefile validate-schema
Validating clustergroup schema of:  ./values-global.yaml ./values-group-one.yaml ./values-hub.yaml
With an error in values-global.yaml:
$ make -f common/Makefile validate-schema
Validating clustergroup schema of:  ./values-global.yamlError: values don't meet the specifications of the schema(s) in the following chart(s): …

Introduce a validate-schema Makefile target

---

clustergroup/values.schema.json

We saw the following error in one of the QE jobs:
Error: values don't meet the specifications of the schema(s) in the following chart(s):
pattern-clustergroup:
- clusterGroup.managedClusterGroups.0.helmOverrides.0.value: Invalid type. Expected: string, given: boolean
It can be that the value associated with helmOverride[x].value is also a
boolean and not only a string, so let's relax this restriction.

helmOverride.value can be both a string and a boolean

---

clustergroup/values.schema.json

There are different vlaues files around where subscriptions is defined
but unset (values-group-one.yaml is currently an example).
check-jsonschema will barf on these with:
$.clusterGroup.subscriptions: None is not of type 'array'
Let's allow them to be defined but set to nothing (aka null)

Allow subscriptions to be null

---

Changes.md
ansible/playbooks/acm/acmhub-get-ca.yaml
ansible/roles/vault_utils/tasks/main.yml
ansible/roles/vault_utils/tasks/vault_spokes_init.yaml
clustergroup/templates/imperative/unsealjob.yaml
golang-external-secrets/templates/golang-external-secrets-hub-secretstore.yaml
golang-external-secrets/values.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml
tests/golang-external-secrets-industrial-edge-factory.expected.yaml
tests/golang-external-secrets-industrial-edge-hub.expected.yaml
tests/golang-external-secrets-medical-diagnosis-hub.expected.yaml
tests/golang-external-secrets-naked.expected.yaml
tests/golang-external-secrets-normal.expected.yaml

This change does three main things:
1. It extends the vault unseal job on the hub with a few tasks that fetch all
non-hub ACM clusters and for each cluster it connects to the remote
cluster API endpoint, fetches the golang-external-secret SA token
and uses it to configure the secret auth/<clusterfqdn>/config
kubernetes vault backend. If no clusters exist, the additional tasks
do nothing. Furhtermore, the tasks are also idempotent.
2. It adds a job called acmhub-ca-cronjob on the non-hub clusters which
will fetch the ACM hub's CA and put it in a secret called "hub" in
the imperative namespace. Idempotent and noop when the cluster is not
part of ACM
3. When the golang-external-secrets chart is included on a spoke
cluster, it will automatically point to the vault on the hub
With this change …

Extend framework to allow for ESO on ACM-imported clusters

---

scripts/pattern-util.sh

This container is managed and build via the utility-container repository
in our github organization. Main reason for switching is size (1.1G vs
2.6G) but it also seems a bit simpler to maintain via a single
Containerfile.

Switch to quay.io/hybridcloudpatterns/utility-container

---

scripts/pattern-util.sh

As reported by Jonny this might be problematic on some Mac OSX versions.
While the investigation still needs to be done, we can safely drop this
additional mount point because in the 'validate-origin' target we are
currently skipping the 'git ls-remote' call when running inside the
container.
We can reassess this at a later time and debug all these corner case,
but it will only make sense if we run the git ls-remote check in the
container as well.

Drop SSH_SOCK_MOUNT from pattern-util.sh

---

Changes.md
acm/templates/policies/application-policies.yaml
clustergroup/templates/plumbing/applications.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-normal.expected.yaml

Tested this with MCG and got the following:
* On the cluster-wide instance on the hub:
/values-global.yaml, /values-hub.yaml, /values-AWS.yaml, /values-AWS-4.11.yaml, /values-AWS-hub.y
aml, /values-4.11-hub.yaml, /values-mcg-hub.yaml
* On the namespaced instance on the hub:
/values-global.yaml, /values-hub.yaml, /values-AWS.yaml, /values-AWS-4.11.yaml, /values-AWS-hub.y
aml, /values-4.11-hub.yaml
* On the imported cluster on the cluster-wide argo instance:
/values-global.yaml, /values-group-one.yaml, /values-AWS.yaml, /values-AWS-4.11.yaml, /values-AWS
-group-one.yaml, /values-4.11-group-one.yaml
* On the imported cluster on the namespaced argo instance:
/values-global.yaml, /values-group-one.yaml, /values-AWS.yaml, /values-AWS-4.11.yaml, /values-AWS
-group-one.yaml, …

Add /values-<platform>.yaml and /values-<platform>-<clusterversion>.yaml support

---

scripts/pattern-util.sh

Tested on Fedora and on Mac OSX. We use the grep -E on the '\b' word
boundary to be a bit more resilient in our grep.

Bail out on unsupported podman versions

---

Makefile
clustergroup/templates/core/catalog-sources.yaml
clustergroup/test.yaml
clustergroup/values.schema.json
operator-install/templates/pattern.yaml

QE needs the ability to deploy patterns with a specific set of CatalogSources corresponding to pre-release operator versions.
This PR facilitates that without requiring deployment specific git commits.

Define pre-release catalog sources from the install command line

---

acm/templates/policies/acm-hub-ca-policy.yaml
acm/templates/policies/application-policies.yaml
acm/templates/policies/ocp-gitops-policy.yaml
tests/acm-industrial-edge-factory.expected.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-naked.expected.yaml
tests/acm-normal.expected.yaml

All other objects under common/acm already have this sync-option.
Now the reason this is mandatory is because during sync-wave: -1 we
create the "kind: MultiClusterHub" which actually installs the operator
which creates all the ACM objects we then use (PlacementRules,
PlacementBindings, Policies). Then during the default sync-wave ("0") we
create all other objects.
The most astute reader will wonder why this is needed at all, since on
paper, on wave "-1" MCH gets created/installed and later during wave "0"
all the objects dependent on MCG should be installed. Well, buckle up,
my friend:
Argo will just straight out refuse to proceed syncing any object (MCH
included) unless those objects have the SkipDryRunOnMissingResource=true
annotation set. In this case sync-waves do not matter *at …

Add SkipDryRunOnMissingResource=true to all PlacementRules

---

scripts/pattern-util.sh

It is already quoted above, so there is no need for the additional
quoting which is actually harmful when it is already unset
as we are going to pass down an empty '' to podman which will be
confused.

Do not quote KUBECONF_ENV

---

ansible/roles/vault_utils/README.md
ansible/roles/vault_utils/tasks/push_secrets.yaml

One point of feedback received lately, was that having
~/values-secrets*yaml files straight in the ~ folder can clutter the
home folder. Add support for storing them inside the ~/.patterns folder.
Overriding the location completely via VALUES_SECRET is still supported.

Add support for ~/.config/hybrid-cloud-patterns folder to store secrets

---

Makefile

See https://github.com/github/super-linter/issues/3786#issuecomment-1444923003

Fix .git missing warnings when running super-linter locally

---

Makefile

So this commit aims to tweak the `install` make target so that it can be
invoked whenever we need to tweak things like git branch or git repo via
CLI but the VP pattern has been installed via the OperatorHub.
Currently if you just run `make install` from the repo after the
operator has been installed via the Web UI, there will be an error like:
```
Error: rendered manifests contain a resource that already exists. Unable
to continue with install: Pattern "multicloud-gitops" in namespace
"openshift-operators" exists and cannot be imported into the current
release: invalid ownership metadata; label validation error: missing key
"app.kubernetes.io/managed-by": must be set to "Helm"; annotation
validation error: missing key "meta.helm.sh/release-name": must be set
to "multicloud-gitops"; …
```

Add more logic to `install` target

---

clustergroup/values.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml

We want to stay up-to-date as to what image containing ansible we use.
https://catalog.redhat.com/software/containers/ansible-automation-platform-23/ee-supported-rhel8/62c7060bc1d77e67d5893a78
This image contains ansible 2.14.3 and kubernetes.cor 2.3.2:
$ podman run -it --rm --net=host --entrypoint /bin/bash registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest -c "ansible-galaxy collection list|grep kubern"
kubernetes.core         2.3.2
Tested on an MCG deployment

Switch to ansible-automation-platform-23/ee-supported-rhel8:latest image by default

---

ansible/plugins/module_utils/load_secrets_v2.py
ansible/tests/unit/test_vault_load_secrets_v2.py
ansible/tests/unit/v2/values-secret-v2-base.yaml
ansible/tests/unit/v2/values-secret-v2-files-emptypath.yaml
ansible/tests/unit/v2/values-secret-v2-files-wrong-onmissingvalue.yaml
ansible/tests/unit/v2/values-secret-v2-files-wrongpath.yaml
ansible/tests/unit/v2/values-secret-v2-onlygenerate.yaml
ansible/tests/unit/v2/values-secret-v2-test-override.yaml

Sometimes they cause issues with some usage in patterns. Let's just drop
them from the default policy.

Drop dollar sign from default password policy

---

ansible/roles/vault_utils/tasks/vault_spokes_init.yaml

- Make sure clusters always has an empty default
- Do not validate certs when we use letsencrypt on the endpoints

Prep Work for letsencrypt support

---

Changes.md
acm/templates/policies/ocp-gitops-policy.yaml
tests/acm-industrial-edge-factory.expected.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-naked.expected.yaml
tests/acm-normal.expected.yaml

The subscription for the gitops policy is controlled by the operator.
If a user changes the gitops subscription channel via the operator,
ACM will actually override this and push its own channel.
Tested via MCG:
* Before the fix
1. Installed the hub via the UI and chose "stable" as the gitops channel
2. Observed that once ACM started applying policies the gitops
subscription was "upgraded" to gitops-1.8
* After the fix
1. Installed the hub via the UI and chose "stable" as the gitops channel
2. Observed that once ACM started applying policies the gitops
subscription stayed the same on the hub

Do not apply the ocp-gitops-policy on the hub via ACM

---

acm/templates/policies/ocp-gitops-policy.yaml
acm/values.yaml

Let's derive it from main.gitops.channel just like we do in other
places.
Tested on an MCG hub/spoke setup and set the following values:
main:
gitops:
channel: "gitops-1.7"
Correctly observed gitops-1.7 installed on both hub and cluster

Do not hardcode the gitops version that gets installed on spokes

---

examples/kustomize-renderer/kustomize

In the same vein as Industrial Edge 57f41dc135f72011d3796fe42d9cbf05d2b82052
we call kustomize build.
Newer gitops versions dropped the openshift-clients rpm by default which
contained kubectl. Let's just invoke "kustomize" directly as the binary
is present in both old and new gitops versions
Since "kubectl kustomize" builds the set of resources by default, we
need to switch to "kubectl build" by default
We also use the same naming conventions used in Industrial Edge while
we're at it.

Fix up kustomize example

---

clustergroup/templates/plumbing/argocd.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml

This allows argo to continue rolling out the rest of the applications whenever a PVC is in a pending status, which presents a chicken/egg scenario for a deployment/deploymentConfig depending on that PVC.  The storageclass bindingmode is `WaitForFirstConsumer` in the hyperscalers, and to override this we would either need to make a separate storageclass with `Immediate` volumebinding and change the order of deployment.
With health check implemented, when the pvc is pending, bound it is considered healthy, and when it reports an error will show as unhealthy. 
Without the health check the application is stuck in a progressing state and will not continue thus preventing any downstream application from deploying.
This directly affects devsecops because we create a pvc for when the pipeline …

Added health check for pvc resource in argocd.yaml

---

scripts/pattern-util.sh

When running the `pattern.sh` script multiple times, a lot of podman exited containers will be left on the machine:
```
CONTAINER ID  IMAGE                                                                                           COMMAND               CREATED       STATUS                    PORTS                                                                   NAMES
726758c9a50a  quay.io/hybridcloudpatterns/utility-container:latest                                            /usr/local/bin/de...  47 hours ago  Exited (0) 47 hours ago                                                                           nostalgic_dubinsky
5adc09db3f70  quay.io/hybridcloudpatterns/utility-container:latest                                            make help             46 hours ago  Exited (0) 46 hours …
```

Avoid exited containers proliferation using pattern.sh script

---

Makefile

This is especially useful when multiple people are working on a pattern
an have been using different names:
$ make help |grep Pattern:
Pattern: multicloud-gitops
$ make NAME=foobar help |grep Pattern:
Pattern: foobar

Allow overriding the pattern's name

---

ansible/roles/iib_ci/tasks/fetch-operator-images.yml

Without also grepping for the default_channel we can end up getting
multiple results, which breaks everything.
Tested this and it fixed the issue I was seeing with the
openshift-gitops-operator this morning

Improve the grepping for the operator bundle

---

ansible/ansible.cfg

display_skipped_hosts=False has a horrible side-effect:
When a task takes a long time, it is always the *next* task and not the
one printed on the screen/log. That is because ansible has to wait for
the task to finish before printing it as it does not know before hand if
the host will be skipped and hence the task should not be displayed at
all

Drop display_skipped_hosts

---

Changes.md
Makefile
clustergroup/templates/plumbing/argocd.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml

Via https://issues.redhat.com/browse/GITOPS-2761 we are told that the
dex configuration has a new format.
Old format:
spec:
dex:
openShiftOAuth: true
resources:
...
New format:
spec:
sso:
provider: dex
dex:
openShiftOAuth: true
resources:
...
This format is only supported starting with gitops-1.8.0, so we should
merge this only when we are absolutely sure that no pattern in no
situation needs an older gitops version.
Tested on MCG with gitops-1.8.2
Note: with this change gitops < 1.8 is not supported. Starting with
gitops-1.9 the old format will be unsupported.

Move to new spec format for dex/sso

---

ansible/roles/iib_ci/tasks/setup-internal-registry.yml

Seems we hit https://www.github.com/containers/podman/issues/13691 at
least with older podman versions.
If this turns out to break podman 4.5.0 I will special case it later

Drop https:// from podman login

---

acm/templates/multiclusterhub.yaml
acm/values.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-naked.expected.yaml
tests/acm-normal.expected.yaml

We set it by default to "redhat-operators" and if defined to .Values.clusterGroup.subscriptions.acm.source
The reason we do this is the following:
1. In a default deployment scenario MCE has to be deployed as normal
from the redhat-operators catalogSource just as ACM is
2. When we deploy gitops-operator from an IIB instead, MCE would be
installed trying to get it from the IIB because
https://www.github.com/stolostron/multiclusterhub-operator/pull/975
made it so that it picks the latest version looking at all catalog
sources. But since we only mirrored the gitops operator in the
cluster, this breaks as the images for MCE from the IIB are not there
By setting the default to "redhat-operators" we fix this case
3. Now in the case where we want to install ACM from an IIB we need to
be able to …

Set the mce-subscription-spec annotation

---

clustergroup/templates/plumbing/applications.yaml

Via https://github.com/hybrid-cloud-patterns/patterns-operator/pull/74
we add the extraParams in an extraParametersNested dictionary that holds
the extraParams key/value pairs. If they exist, let's add them as
parameters.
This allows them to end up in the applications.

Add support for extraParams being passed down to all applications

---

operator-install/templates/subscription.yaml
operator-install/values.yaml

This will allow us to test the patterns-operator using a different
catalogsource (potentially installed via an IIB). So we can run:
make EXTRA_HELM_OPTS="\
--set main.extraParameters[0].name=main.patternsOperator.channel --set main.extraParameters[0].value=slow \
--set main.extraParameters[1].name=main.patternsOperator.source --set main.extraParameters[1].value=patten-index" install

Allow overriding channel and source when installing the patterns-operator

---

ansible/roles/vault_utils/tasks/push_secrets.yaml

When HOME is set we replace it with '~' in this debug message
because when run from inside the container the HOME is /pattern-home
which is confusing for users. Printing out '~' when at the start of
the string is less confusing.
Before:
ok: [localhost] => {
"msg": "/home/michele/.config/hybrid-cloud-patterns/values-secret-multicloud-gitops.yaml"
}
After:
ok: [localhost] => {
"msg": "~/.config/hybrid-cloud-patterns/values-secret-multicloud-gitops.yaml"
}

Tweak the load secret debug message to be clearer

---

clustergroup/Chart.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml

We currently have a small inconsistency where we use common/clustergroup
in order to point Argo CD to this chart, but the name inside the chart
is 'pattern-clustergroup'.
This inconsistency is currently irrelevant, but in the future when
migrating to helm charts inside proper helm repos, this becomes
problematic. So let's fix the name to be the same as the folder.
Tested on MCG successfully.

Clustergroup Chart.yaml name change

---

scripts/pattern-util.sh

If it is somewhere under /tmp, bail out explaining why. This has caused
a few silly situations where the user would save the KUBECONFIG file
under /tmp. Since bind-mounting /tmp seems like a wrong thing to do in
general, we at least bail out with a clear error message.
To do this we rely on a bash functionality so let's just switch the
script to use that.
export KUBECONFIG=/tmp/kubeconfig
./scripts/pattern-util.sh make help
/tmp/kubeconfig is pointing inside the /tmp folder, this will make it unavailable from the container.
Please move it somewhere inside your /home/michele folder, as that gets bind-mounted inside the container
export KUBECONFIG=~/kubeconfig
./scripts/pattern-util.sh make help
Pattern: common
Usage:
make <target>
...

Check if the KUBECONFIG file is inside /tmp

---

acm/templates/provision/clusterpool.yaml
tests/acm-normal.expected.yaml

Currently with the following values snippet:
managedClusterGroups:
exampleRegion:
name: group-one
acmlabels:
- name: clusterGroup
value: group-one
helmOverrides:
- name: clusterGroup.isHubCluster
value: false
clusterPools:
exampleAWSPool:
size: 1
name: aws-ap-bandini
openshiftVersion: 4.12.24
baseDomain: blueprints.rhecoeng.com
controlPlane:
count: 1
platform:
aws:
type: m5.2xlarge
workers:
count: 0
platform:
aws:
region: ap-southeast-2
clusters:
- One
You will get a clusterClaim that is pointing to the wrong Pool:
NAMESPACE                 NAME                       POOL
open-cluster-management   one-group-one              aws-ap-bandini
This is wrong because the clusterPool name will be generated using the
pool name + "-" group name:
{{- $pool := . }}
{{- $poolName := print .name "-" …

Fix the clusterPoolName in clusterClaims

---

clustergroup/templates/plumbing/applications.yaml

Let's improve readability by adding some comments to point out which
flow constructs are being ended.

Add some comments to make if/else and loops clearer

---

ansible/roles/vault_utils/tasks/vault_spokes_init.yaml

Noticed that the service account & namespace vars were mixed around for spoke vault configs.
It is not normally noticeable since they default to the same value, but in my situation I have them different.
This led to noticing the following error in my clustersecretstores:
```
Code: 403. Errors:
* namespace not authorized`
```

Fix sa/namespace mixup in vault_spokes_init

---

Makefile

If you call the load-iib target you *must* set INDEX_IMAGES, so
let's error out properly if you do not.

Error out from load-iib when INDEX_IMAGES is undefined

---

ansible/roles/iib_ci/tasks/fetch-operator-images.yml

The current -w grep command matches channels even when they are
substrings of each other like for the serverless-operator:
$ podman run -i --rm $INDEX_IMAGES alpha list channels /configs "${OPERATOR}" |grep --word-regexp "stable"
serverless-operator  stable       serverless-operator.v1.30.0
serverless-operator  stable-1.29  serverless-operator.v1.29.1
serverless-operator  stable-1.30  serverless-operator.v1.30.0
This then causes error when trying to parse the list of images as we
will have multiple images because we break the one image per line
assumption.
Let's fix this by adding spaces around the grep. Ideall we'd use the
opm render command, but the parsing of all the yaml output seems a bit
much to do for this simple use case.

Fix fetching the bundle name when loading an IIB

---

.github/workflows/chart-branches.yml
.github/workflows/chart-split.yml

This will push any change done to a chart folder out into the separate
repo corresponding to the chart that has been changed.
This workflow needs a secret called CHARTS_REPOS_TOKEN that is a
Personal Access Token with fine grained repo and workflow write access
on the following repos:
- acm-chart
- hashicorp-vault-chart
- golang-external-secrets-chart
- clustergroup-chart
- letsencrypt-chart

Add workflow to split helm charts into their own repo

---

.github/workflows/chart-branches.yml

Otherwise a push to a private for to main would still invoke the split
workflow, if a member of the vp org would do so. Since we do not want
that let's make sure we limit this workflow to when the repository name
is 'validatedpatterns/common'

Make sure we run the split workflow only when the changes land in validatedpatterns/common

---

operator-install/templates/pattern.yaml

The inclusion condition for the extraValueFiles was inadvertently inside the one for extraParameters, so extraValueFiles would only be included if there were also extraParameters.
Also quote extraParameter name and value "values".

Correct ifs and ranges in pattern, add comments

---

hashicorp-vault/values.yaml
tests/hashicorp-vault-industrial-edge-factory.expected.yaml
tests/hashicorp-vault-industrial-edge-hub.expected.yaml
tests/hashicorp-vault-medical-diagnosis-hub.expected.yaml
tests/hashicorp-vault-naked.expected.yaml
tests/hashicorp-vault-normal.expected.yaml

It is not needed and it adds a requirement to the cluster to have a
proper LadBalancer which is not always the case.
The default in the helm chart is "ClusterIP", so let's leave that
default.
Tested this on an OCP 4.13 SNO cluster (without LB) and the UI is
correctly accessible.

Drop vault.ui.serviceType: "LoadBalancer"

---

Changes.md
clustergroup/templates/_helpers.tpl
clustergroup/templates/plumbing/applications.yaml
clustergroup/values.schema.json

This change adds initial multiSource support to patterns' applications.
The way this works is that nothing changes for applications defined in
values-*.yaml by default. So all patterns will work as usual.
What can change with this patch is that applications can slowly migrate
towards using multi source by changing an app definition from:
acm:
name: acm
path: common/acm
To:
acm:
name: acm
chart: acm
chartVersion: 0.0.*
So any time we have a `chart` field with a `chartVersion` and no
`repoURL` defined, the clustergroup chart will create a multisource
application with the values files taken from the patterns git repo
and the helm chart from https://charts.validatedpatterns.io/ using
the `chartVersion` defined in the application.
For example the above acm app would prodice the following: …

Add initial multi-source support

---

operator-install/crds/gitops.hybrid-cloud-patterns.io_patterns.yaml

This is needed if we want to support multisource installations from the
CLI

Update crd in common

---

scripts/pattern-util.sh

Currently a user can set additional helm params via the
EXTRA_HELM_OPTS environment variable in order to tweak a value at `make
install` time.
This does not work correctly when we run things from our utility
container, that is because that variable is never passed from the host
to the container.
According to `man podman run` if we simply pass `-e EXTRA_HELM_OPTS` to
the podman invocation: "If an environment variable is spec‐
ified without a value, Podman checks the host environment for a value
and set the variable only if it is set on the host"
* Without setting EXTRA_HELM_OPTS:
unset EXTRA_HELM_OPTS; ./pattern.sh make install
make -f common/Makefile operator-deploy
Checking prerequisites:
Check for …

Add support for passing EXTRA_HELM_OPTS

---

.github/workflows/linter.yml
clustergroup/values.schema.json
operator-install/templates/pattern.yaml
operator-install/values.yaml
tests/operator-install-industrial-edge-factory.expected.yaml
tests/operator-install-industrial-edge-hub.expected.yaml
tests/operator-install-medical-diagnosis-hub.expected.yaml
tests/operator-install-naked.expected.yaml
tests/operator-install-normal.expected.yaml

Via:
```
export EXTRA_HELM_OPTS="--set main.multiSourceConfig.enabled=true"
```
one can now deploy a pattern with the experimental multisource support
enabled.
Tested with the above command and correctly deployed a multi-source
based pattern.

Add support for deploying multi source via CLI

---

Makefile
README.md
ansible/roles/vault_utils/README.md
ansible/roles/vault_utils/tasks/push_secrets.yaml

* Pristine environment:
$ make show
helm template common/operator-install/ --name-template common -f values-global.yaml --set main.git.repoURL="https://github.com/hybrid-cloud-patterns/common.git" --set main.git.revision=vp-paths
---
apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
name: common
namespace: openshift-operators
spec:
clusterGroupName: example
gitSpec:
targetRepo: https://github.com/hybrid-cloud-patterns/common.git
targetRevision: vp-paths
gitOpsSpec:
operatorChannel: gitops-1.8
operatorSource: redhat-operators
multiSourceConfig:
enabled: false
...
* Add UUID to the environment
$ echo "vp-team-bandini" >> ~/.config/validated-patterns/pattern-uuid
$ make show
helm template common/operator-install/ --name-template common -f values-global.yaml --set …

Add support for ~/.config/validated-patterns/pattern-uuid

---

clustergroup/templates/plumbing/applications.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-normal.expected.yaml

feat:  Add labels to ArgoCD applications created by the VP framework.
PR relates to the work in [MBP-184] Operator: Update status section based on argo application state(s). This PR adds a label that the operator will query for all the applications that are part of a VP pattern. The operator will retrieve the applications and add the status information in the pattern CR. 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
annotations:
finalizers:
- resources-finalizer.argocd.argoproj.io/foreground
labels:
app.kubernetes.io/instance: multicloud-gitops-hub
validatedpatterns.io/pattern: multicloud-gitops
name: acm
namespace: multicloud-gitops-hub
spec:
destination:
name: in-cluster
namespace: open-cluster-management
ignoreDifferences:
...
syncPolicy:
automated: {}
retry:
limit: …
```

Adding label validatedpatterns.io/pattern to all applications.

---

Makefile

Drop the old logic and just install the CRD via OC and use helm template
for the rest.
The rationale is that helm install is very picky whenever it encounters
things that already exist. We have three potential scenarios at work
here:
A) User installs operator+pattern via CLI and updates the pattern via
CLI (this worked before this change as well)
B) User installs operator+pattern via UI but runs updates (changing
branch for example) via CLI (this worked before this change as well)
C) User installs only the operator via UI. Installs and updated the
pattern via CLI. This was broken before this change. The error you'd
get was:
```
...
https://github.com/mbaldessari/multicloud-gitops.git - branch main: Running inside a container: Skipping git ssh checks
+ oc get crds …
```

Rework installation target

---

clustergroup/templates/plumbing/argocd.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml

Our resourceCustomization is currently giving the following warning:
Warning  DeprecationNotice  27m         ResourceCustomizations is
deprecated, please use the new formats `ResourceHealthChecks`,
`ResourceIgnoreDifferences`, and `Resource Actions` instead.
This actually becomes a problem with gitops-1.10 because it dropped
support for v1alpha versions of argoCD (it upgrades them automatically
to v1beta). So the cluster-wide argo app which is in charge of creating
the namespaced argoCD instance will always be OutOfSync as it will never
be able to set the `resourceCustomization` field.
Move to resourceHealthcheck which is the new supported way. This is also
backwards compatible with gitops-1.8.
1. Deployed 4.13 with gitops-1.10 and observed the multicloud-gitops-hub …

Move from resourceCustomization to resourceHealthcheck

---

Makefile

This is a simple quick check to see if all argo applications in all
namespaces are synced and error out if they are not.
Synced example:
$ make argo-healthcheck
make -f common/Makefile argo-healthcheck
Checking argo applications
multicloud-gitops-hub acm -> Synced
multicloud-gitops-hub config-demo -> Synced
multicloud-gitops-hub golang-external-secrets -> Synced
multicloud-gitops-hub hello-world -> Synced
multicloud-gitops-hub vault -> Synced
openshift-gitops multicloud-gitops-hub -> Synced
Not synced example:
$ make argo-healthcheck
make -f common/Makefile argo-healthcheck
make[1]: Entering directory …

Introduce an argo-healthcheck make target

---

scripts/pattern-util.sh

From https://docs.podman.io/en/latest/markdown/podman-run.1.html#pull-policy
Pull image policy. The default is missing.
always: Always pull the image and throw an error if the pull fails.
missing: Pull the image only if it could not be found in the local
containers storage. Throw an error if no image could be found and
the pull fails.
never: Never pull the image but use the one from the local containers
storage. Throw an error if no image could be found.
newer: Pull if the image on the registry is newer than the one in
the local containers storage. An image is considered to be newer
when the digests are different. Comparing the time stamps is prone
to errors. Pull errors are suppressed if a local image was found.
Switching to pull=newer will allow us to keep this image uptodate for
users …

Add --pull=newer when running the container

---

clustergroup/templates/imperative/job.yaml

Tested by commenting out the whole `imperative` section in values-hub
and deploying MCG.

Allow imperative to be nil

---

clustergroup/templates/plumbing/applications.yaml

Add the toPrettyJson call where it is missing to ensure `plugin:` settings can be arbitrary objects and will be consistent. No tests or schemas need to change for this.

Make .plugin handling consistent

---

operator-install/templates/pattern-operator-configmap.yaml
tests/operator-install-industrial-edge-factory.expected.yaml
tests/operator-install-industrial-edge-hub.expected.yaml
tests/operator-install-medical-diagnosis-hub.expected.yaml
tests/operator-install-naked.expected.yaml
tests/operator-install-normal.expected.yaml

This way we keep the main.gitops keys working which is needed for IIB
installs.
Tested with:
export EXTRA_HELM_OPTS="--set main.gitops.channel=gitops-1.10"
and correctly got gitops from 1.10 installed.

Preseed the patterns-operator-config configmap

---

clustergroup/templates/core/operatorgroup.yaml
clustergroup/values.schema.json
examples/values-example.yaml
tests/clustergroup-normal.expected.yaml

Implements the issue describe in [Issue #296 ](https://github.com/validatedpatterns/common/issues/296)
- Added operatorgroupExcludeTargetNS key to exclude targetNamespace in an Operator Group

Adding key to exclude target namespace in operatorgroup

---

golang-external-secrets/templates/golang-external-secrets-hub-secretstore.yaml
golang-external-secrets/values.yaml

This will allow users to disable using the default kube-root-ca.crt
configmap and/or customize things fully.
So, for example, an environment which uses letsencrypt for the ingress
certs, but does not have that CA included in kube-root-ca.crt, can
simply override things with a /values-IBMCloud.yaml file with:
caProvider:
enabled: false
Which will just use the CA System bundle to authenticate connections
from ESO to vault.

Parametrize ESO caProvider fields

---

ansible/roles/iib_ci/tasks/mirror-related-images.yml
ansible/roles/iib_ci/templates/mirror.map.j2

- Updated the Jinja2 template *ansible/roles/iib_ci/templates/mirror.map.j2* to add a '<iibnumber>-<count>' to the image tag if there's a source image that has the same name in the mirror.map file.
Example mirror.map entry:
registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:da5d5061dbc2ec5082cf14b6c600fb5400b83cf91d7ccebfa80680a238d275db=default-route-openshift-image-registry.apps.lc-claudiol-devsec-hub-535d-2.blueprints.rhecoeng.com/openshift-marketplace/ose-kube-rbac-proxy:610968
registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:d4de33150cb8c8faf0133b39553e6c972be5ace7ae787c98f3b77fca37748036=default-route-openshift-image-registry.apps.lc-claudiol-devsec-hub-535d-2.blueprints.rhecoeng.com/openshift-marketplace/ose-kube-rbac-proxy:610968
The above will generate an error in …

Fix: bug in task TASK [iib_ci : Mirror all the needed images]

---

acm/.github/workflows/update-helm-repo.yml
clustergroup/.github/workflows/update-helm-repo.yml
golang-external-secrets/.github/workflows/update-helm-repo.yml
hashicorp-vault/.github/workflows/update-helm-repo.yml
letsencrypt/.github/workflows/update-helm-repo.yml

Reason is that even though we've updated workflows in helm-chart, the
charts seem to still reference the an old commit:
validatedpatterns/helm-charts/.github/workflows/helmlint.yml@refs/tags/main (ee7ec78f30b8f72463633b781527dfa186d3e980)

Stop referencing remote actions via @main. Use a specific commit

---

ansible/roles/vault_utils/tasks/push_secrets.yaml

Sometimes CI would error out with:
[localhost]: FAILED! => {"msg": "The conditional check
'vault_role_cmd.rc == 0' failed. The error was: error while evaluating
conditional (vault_role_cmd.rc == 0): 'dict object' has no attribute
'rc'. 'dict object' has no attribute 'rc'"}
This can ahepn when a call returns error 500 for whatever reason.
Let's make sure we catch this situation and keep trying and don't give
up due to this spurious error.

Check for rc attribute to exist

---

ansible/roles/iib_ci/templates/imageDigestMirror.yaml.j2

Currently when we load a preview operator via the IIB mechanism we
redirect all images making up the operator bundle to the
cluster-internal registry. This is all fine and well, except these
redirects (done via an ImageDigestMirrorSet) are based on image names
without any specific hashes. (This is because OCP won't allow
you to specify hashes).
The problem arises when there is a prerelease operator which includes an
image that is used by the other non-prerelease operators. So if AAP
prerelease uses the image "registry.redhat.io/public/redis-6" we
redirect all these redis 6 images towards the internal registry.
But if another operator needs the redis-6 image with a hash that is not
the exact same that is used by AAP prerelease, it will be unable to find
it on the internal registry because …

Switch imageDigestMirrors to AllowContactingSource

---

operator-install/templates/pattern.yaml
operator-install/values.yaml

Tested with:
export EXTRA_HELM_OPTS="--set main.tokenSecret=private-repo --set main.tokenSecretNamespace=openshift-operators"
Note that this is currently only working with https URLs because we have
logic in the Makefile to rewrite ssh-based git URLs into https ones.

Add initial support for deploying private repos via CLI directly

---

scripts/pattern-util.sh

The addition of --userns keep-id:uid=...,gid=... is supported only on
podman versions >= 4.3.0 [1]
If we have an older version, let's just keep the same logic as before.
[1] https://github.com/containers/podman/blob/main/troubleshooting.md#39-podman-run-fails-with-error-unrecognized-namespace-mode-keep-iduid1000gid1000-passed

Account for podman versions older than 4.3.0

---

operator-install/values.yaml
tests/operator-install-industrial-edge-factory.expected.yaml
tests/operator-install-industrial-edge-hub.expected.yaml
tests/operator-install-medical-diagnosis-hub.expected.yaml
tests/operator-install-naked.expected.yaml
tests/operator-install-normal.expected.yaml

Tested on both ocp 4.14 and 4.12.
4.12 is the oldest supported version at this point in time.

Switch default gitops channel to gitops-1.11

---

scripts/pattern-util.sh

The reason for this is somewhat multi-faceted, but boils down to the
fact that openssh does not consult the $HOME variable to find .ssh/*
files but only relies to the home folder entry in /etc/passwd.
So what might happen is the following scenario:
1. The remote is ssh based: `origin  git@github.com:validatedpatterns/industrial-edge`
2. The main Makefile invokes `git remote show origin` which triggers an ssh connection
3. The ssh connection fails because ssh ignores the $HOME variable and instead relies on the home in `getent passwd`. Which is set to:
```
fedora:*:1000:1000:fedora Cloud User:/home/fedora/industrial-edge:/bin/sh
```
4. Newer podmans set the user's home folder automagically to the folder
that is passed as current working directory (in our case we pass `-w
$(pwd)`)
Under …

Set the user's passwd entry inside the container

---

.github/workflows/linter.yml

This is the version we use in gitops-1.11 which is the new default

Upgrade helm to v3.13.2

---

Makefile

There is no point in testing the requirements when we use the container,
as we guarantee that those exist in there.
❯ make validate-prereq
make -f common/Makefile validate-prereq
Checking prerequisites:
Check for 'git helm oc ansible': OK
Check for python-kubernetes: OK
Check for kubernetes.core collection: OK
❯ ./pattern.sh make  validate-prereq
make -f common/Makefile validate-prereq
Skipping prerequisites check as we're running inside a container
make[1]: Leaving directory …

Run validate-prereq only when not in a container

---

acm/templates/policies/ocp-gitops-policy.yaml
acm/values.yaml
tests/acm-industrial-edge-factory.expected.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-naked.expected.yaml
tests/acm-normal.expected.yaml

This is mainly for consistency reasons as the value is taken from
main.gitops anyways.

Use gitops-1.11 in acm as well

---

operator-install/templates/pattern.yaml
reference-output.yaml

Mainly for consistency reasons. gitops-1.11 is already the default

Small gitops channel cleanups

---

acm/templates/_helpers.tpl
acm/templates/policies/application-policies.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-normal.expected.yaml

When applying the policy to install the cluster-wide argo on regional
clusters, we do some lookups() on the regional cluster in order to
pass the version values, domain names, etc.
To get the cluster version we were using the OpenShiftControllerManager
which is problematic because it does not exist on hyper-shift clusters.
Let's switch to use the ClusterVersion.status.history[0].version entry.
The only smaller caveat is that due to limitations in go templates +
sprig functions, we cannot really take the last version only when the
state is "Completed", but we simply take the last version.
This means that during a cluster upgrade on a regional cluster, we will
include values of the version the cluster is upgrading to, which is
less than ideal, but it should eventually converge in any case. …

Stop using OpenShiftControllerManager lookups

---

scripts/pattern-util.sh

This is useful whenever a custom CA is installed on the system and is
needed to connect to a remote cluster.

Bind mount /etc/pki in the wrapper

---

scripts/preview-all.sh

Before:
$ ./pattern.sh make preview-all
make -f common/Makefile preview-all
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
1. Via the command-line flag --kubeconfig
2. Via the KUBECONFIG environment variable
3. In your home directory as ~/.kube/config
To view or setup config directly use the 'config' command.
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
1. Via the command-line flag --kubeconfig
2. Via the KUBECONFIG environment variable
3. In your home directory as ~/.kube/config
To view or setup config directly use the 'config' command.
...This goes on for many more iterations...
After:
$ …

Properly error out in preview-all when we cannot connect to the cluster

---

scripts/preview.sh

This is because in helm we use "ignoreMissingValueFiles: true". I.e. we
just ignore non existing value files. Let's do the same for the
preview.sh script.
Before:
❯ make preview-all
make -f common/Makefile preview-all
Error: open /home/michele/Engineering/cloud-patterns/multicloud-gitops/overrides/values-None.yaml: no such file or directory
Error: open /home/michele/Engineering/cloud-patterns/multicloud-gitops/overrides/values-None.yaml: no such file or directory
Error: open /home/michele/Engineering/cloud-patterns/multicloud-gitops/overrides/values-None.yaml: no such file or directory
Error: open /home/michele/Engineering/cloud-patterns/multicloud-gitops/overrides/values-None.yaml: no such file or …

Only include values files if they do exist in preview.sh

---

scripts/preview-all.sh
scripts/preview.sh

When `kustomize: true` simply take the path and call `kustomize build
<path>`. In any other case keep using helm for templating.
Before:
...
+ common/scripts/preview.sh hub compliance-operator https://github.com/mbaldessari/multicloud-gitops.git preview-fixes
Error: Chart.yaml file is missing
After:
...
+ common/scripts/preview.sh hub compliance-operator https://github.com/mbaldessari/multicloud-gitops.git preview-fixes
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
name: purpose-banner
spec:
backgroundColor: '#ff0000'
color: '#fff'
location: BannerTop
text: HUBOPS

Do not error out in preview when kustomize: true

---

clustergroup/templates/imperative/unsealjob.yaml
clustergroup/values.schema.json
golang-external-secrets/templates/kubernetes/golang-external-secrets-hub-secretstore.yaml
golang-external-secrets/templates/vault/golang-external-secrets-hub-secretstore.yaml

It is currently not there even though we mention it in the values files.

Add .global.secretStore.backend in the clustergroup schema

---

scripts/preview.sh

This covers the following case:
foobar:
name: foo
namespace: foo
project: foo
path: charts/all/foo
The preview.sh script is passed the name attribute of the application
`foo`. So now we first find the key which corresponds to the attribute
name `foo` and then use that when looking up the other attributes like
path, etc.
Closes: #351

Fix preview when the application's index name is not the same as the name attribute

---

clustergroup/templates/plumbing/applications.yaml

Otherwise if we pass a boolean in the extraParametersNested we will get:
spec.source.helm.parameters[10].value: Invalid value: "boolean":
spec.source.helm.parameters[10].value in body must be of type string:
"boolean"

Force strings in extraParametersNested

---

acm/templates/policies/application-policies.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-normal.expected.yaml

The reason for this is the following:
When changing the repo on the hub (by editing the pattern), the
expectation is that the repo change will replicate from the hub to the
spokes managed by ACM.
Today this is very unlikely to happen because changing the repo on the
hub will not change the policy and so ACM will not reapply it on the
spokes. (I believe there is like a daily repush that happens even when
the policy has not changed, but that is way too slow to be relied upon).
By using the actual variable the policy will actually change, ACM will
notice this and push the change on the spokes.
Found while testing disconnected mode.
I am not replacing them everywhere because I am not sure yet if there are
additional semantics in common/clustergroup that I am unaware of.

In ACM policies do not use $ARGOCD_APP_SOURCE_* variables

---

acm/templates/policies/application-policies.yaml
acm/templates/policies/ocp-gitops-policy.yaml
clustergroup/templates/_helpers.tpl
clustergroup/templates/imperative/_helpers.tpl
clustergroup/templates/imperative/configmap.yaml
clustergroup/templates/imperative/job.yaml
clustergroup/templates/imperative/unsealjob.yaml
clustergroup/templates/plumbing/argocd.yaml
clustergroup/templates/plumbing/trusted-bundle-ca-configmap.yaml
tests/acm-industrial-edge-factory.expected.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-naked.expected.yaml
tests/acm-normal.expected.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml

- **Add support for custom CAs**
- **Update tests**

Custom CA support

---

clustergroup/templates/imperative/_helpers.tpl
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml

If the clusterwide proxy object is configured, let's support it when
we clone the git repos for the imperative framework.

Support for cluster-wide proxy

---

clustergroup/templates/_helpers.tpl
clustergroup/templates/core/namespaces.yaml
clustergroup/templates/core/operatorgroup.yaml
clustergroup/templates/plumbing/projects.yaml
clustergroup/values.schema.json
examples/values-example.yaml

The changes here support the "Support for merging of namespaces, projects,
subscriptions and application in overrides/values-common.yaml #459" issue that was opened by
Northrop Grumman
Files that were changed are:
clustergroup/templates/_helpers.tpl
clustergroup/templates/core/namespaces.yaml
clustergroup/templates/core/operatorgroup.yaml
clustergroup/templates/plumbing/projects.yaml
clustergroup/values.schema.json
examples/values-example.yaml
The idea is that if you define the projects section, or the namespaces section, in two different
values files using a map construct we will be able to merge both definition of projects into
the final rendering of the manifests.
The new structure for projects is as follows:
```
clusterGroup:
...
projects:
project1:
```
The new structure for …

feat: Support for issue #459

---

scripts/preview.sh

This allows us to have a remote repoURL + path kustomize combo and show
the resulting templates in `make preview`.
Tested with:
web-terminal:
name: web-terminal
namespace: hello-world
project: hub
kustomize: true
targetRevision: main
repoURL: https://github.com/redhat-cop/gitops-catalog
path: web-terminal/aggregate/overlays/default
Closes: https://github.com/validatedpatterns/multicloud-gitops/issues/356

Support remote repoURL when previewing templates

---

Makefile

Attempts to 
`source pattern.sh make preview-{myapp}`
currently fail without this change in place,

Moved CLUSTERGROUP declaration to restore make preview-% functionality

---

acm/templates/policies/application-policies.yaml

This corrects Argo error:
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template acm --namespace open-cluster-management --kube-version 1.25 --set global.privateRepo=false --set global.experimentalCapabilities=initcontainers --set global.repoURL=https://github.myrepo.com/EnterpriseKubernetes/multicloud-gitops.git --set global.clusterDomain=mydomain.azure.us --set global.clusterPlatform=Azure --set global.hubClusterDomain=mydomain.azure.us --set global.localClusterDomain=mydomain.azure.us --set global.targetRevision=prod --set global.namespace=open-cluster-management --set global.pattern=ekho --set global.clusterVersion=4.12 --values <path to cached …

bug: Fixes indenting and duplicate entries in application-policies.yaml

---

clustergroup/templates/_helpers.tpl

- Added condition to check if operatorGroup key exists  {{- if or $v.operatorGroup (not (hasKey $v "operatorGroup")) }}
- Default behavior is that we generate an OperatorGroup for a Namespace definition.

bug: Fix to generate OperatorGroup definition when namespaces definition has labels

---

clustergroup/templates/imperative/_helpers.tpl
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml

In case a git repo has some things split over submodules, let's clone
those too.
The version of git in the imperative image is currently:
sh-5.1# git version
git version 2.39.3
Tested with:
sh-5.1# git clone --recurse-submodules --single-branch --branch main --depth 1 -- "https://github.com/validatedpatterns/multicloud-gitops" /tmp/
Cloning into '/tmp'...
remote: Enumerating objects: 426, done.
remote: Counting objects: 100% (426/426), done.
remote: Compressing objects: 100% (343/343), done.
remote: Total 426 (delta 87), reused 221 (delta 40), pack-reused 0
Receiving objects: 100% (426/426), 545.98 KiB | 1.78 MiB/s, done.
Resolving deltas: 100% (87/87), done.
Co-Authored-By: Sergio Garcia Martinez <sgarcia@redhat.com>

Use --recurse-submodules when cloning

---

Makefile
ansible/roles/iib_ci/README.md
ansible/roles/iib_ci/defaults/main.yml
ansible/roles/iib_ci/tasks/fetch-operator-images.yml
ansible/roles/iib_ci/tasks/install-iib-in-cluster.yml
ansible/roles/iib_ci/tasks/main.yml
ansible/roles/iib_ci/tasks/mirror-related-images.yml
ansible/roles/iib_ci/templates/catalogSource.yaml.j2
ansible/roles/iib_ci/templates/imageDigestMirror.yaml.j2

This adds multiple IIB support in order to cater for the ACM IIB case,
where the MCE operator might be in another IIB completely.
To load multiple IIB for different operators, one needs to set the env
variables as follows:
export OPERATOR=advanced-cluster-management,multicluster-engine
export INDEX_IMAGES=registry-proxy.engineering.redhat.com/rh-osbs/iib:713808,registry-proxy.engineering.redhat.com/rh-osbs/iib:718034
It is implied that the first IIB is for the first operator in the list,
and the second one for the latter.
Tested gitops-iib and it all worked with no changes.

Rework IIB loading support

---

acm/templates/policies/ocp-gitops-policy.yaml

- Added new section for to configure the ArgoCD server to support tls
```
global:
argocdServer:
route:
tls:
insecureEdgeTerminationPolicy: Redirect
termination: reencrypt
```
- Default for ArgoCD is to create route with the following:
```
route: enabled
tls:
insecureEdgeTerminationPolicy: Redirect
termination: passthrough
```
For more information please refer to https://issues.redhat.com/browse/GITOPS-3918.

New global scope argocdServer section for values-global.yaml

---

operator-install/templates/pattern.yaml
tests/operator-install-industrial-edge-factory.expected.yaml
tests/operator-install-industrial-edge-hub.expected.yaml
tests/operator-install-medical-diagnosis-hub.expected.yaml
tests/operator-install-naked.expected.yaml
tests/operator-install-normal.expected.yaml

We drive this from the patterns-operator-config configmap these days, which
makes more sense (it is a clusterwide setting and not really a per
pattern one).

Drop gitopsspec from pattern's CR

---

acm/templates/policies/ocp-gitops-policy.yaml

This makes the registry url more consistent with what we already use
(e.g. in the imperative templates)

Switch to registry.redhat.io for the initContainer image

---

acm/templates/policies/application-policies.yaml

- If statement was checking for .Values.global.extraValueFiles.
- We now checking at the .extraValueFiles in the managedClusterGroups section.
managedClusterGroups:
aro-prod:
name: innovation
acmlabels:
- name: clusterGroup
value: innovation
extraValueFiles:
- '/overrides/values-common-capabilities.yaml'
helmOverrides:
- name: clusterGroup.isHubCluster
value: "false"

Update for ACM chart to application-policies.yaml

---

clustergroup/values.schema.json

- Problem Statement
The current **clustergroup** schema does not allow the definition of **extraParameters** under the **main** section of a values file.
- Caveat
The user defined variables in the **extraParameters** section would only be applied if the user deploys the pattern via the command, using `./pattern.sh make install` or `./pattern.sh make operator-deploy` and not via the OpenShift Validated Patterns Operator UI.
- Fix Description
Add the **extraParameters** to the definition of **Main.properties** in the values.schema.json:
"extraParameters": {
"type": "array",
"description": "Pass in extra Helm parameters to all ArgoCD Applications and the framework."
},
- This will allow users to define extra parameters that will be added by the framework to the ArgoCD applications it …

Add extraParameters to values.schema.json

---

acm/templates/policies/application-policies.yaml
clustergroup/templates/plumbing/applications.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-normal.expected.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-normal.expected.yaml

- The operator adds these extraParameters to the extraParametersNested section as key/value pairs in the Cluster Wide ArgoCD Application created by the Validated Patterns operator.
- This update will add the user defined extra parameters on the ArgoCD Applications on the Spoke Clusters.

Feat: Followup to definition of extraParameters under the main section of a values file.

---

acm/templates/policies/acm-hub-ca-policy.yaml
acm/values.yaml
golang-external-secrets/values.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-normal.expected.yaml
tests/golang-external-secrets-industrial-edge-factory.expected.yaml

- **Use golang-external-secrets for the acm hub-ca bits**
- **Only do the acm hub ca policy when vault is the backend**

Updates to acm-hub-ca

---

clustergroup/templates/plumbing/argocd-super-role.yaml
tests/clustergroup-industrial-edge-factory.expected.yaml
tests/clustergroup-industrial-edge-hub.expected.yaml
tests/clustergroup-medical-diagnosis-hub.expected.yaml
tests/clustergroup-naked.expected.yaml
tests/clustergroup-normal.expected.yaml

This is important because in some situations (we've observed this on the
clusterwide argo instance on spokes) the permissions are not there yet
when argo tries to create service accounts for the imperative SAs.
This means that the very first sync works up to the service account
creation which then fails due to lacking RBACs. This triggers a gitops
issue where selfheal never retries because the previous run failed and
so the app is in a stuck loop forever
Co-Authored-By: Jonny Rickard <jrickard@redhat.com>
Closes: GITOPS-4677

Force rolebindings as early as possible

---

clustergroup/templates/_helpers.tpl
clustergroup/templates/core/operatorgroup.yaml
clustergroup/templates/plumbing/applications.yaml
tests/clustergroup-normal.expected.yaml

bug: Invalid OperatorGroup generated when ommitting targetNamespaces
Problem Statement:
When setting a namespace like this:
- openshift-distributed-tracing:
operatorGroup: true
targetNamespaces: []
The chart generates the following yaml:
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
name: openshift-distributed-tracing-operator-group
namespace: openshift-distributed-tracing
spec:
targetNamespaces:
```
Which k8s rejects the targetNamespaces key as invalid when it attempts to apply it and removes it since it doesn't have a value, which just so happens to have the desired result of not setting the targetNamespaces (or a selector) to enable it for All Namespaces.

bug: Invalid OperatorGroup generated when omitting targetNamespaces

---

acm/templates/provision/clusterdeployment.yaml
acm/templates/provision/clusterpool.yaml
acm/templates/provision/managedclusterset.yaml
acm/templates/provision/secrets-aws.yaml
acm/templates/provision/secrets-azure.yaml
acm/templates/provision/secrets-common.yaml
acm/values.yaml
clustergroup/values.schema.json
examples/values-example.yaml
tests/acm-normal.expected.yaml
tests/clustergroup-normal.expected.yaml

- Added feature for creating Spoke Clusters using Hive's [ClusterDeployment API](https://github.com/openshift/hive/blob/master/docs/using-hive.md#clusterdeployment).
- Modified the _clustergroup_ schema; added `clusterDeployments` for a group, used `clusterPools` as a template.
- Modified test cases testing `clusterDeployments` on the same _multiclustergroup_ with `clusterPools` and on its own.
- Multiple Commits in this PR make reviewing easier; these can be squashed together if required.
- If preferred, we can move the tests to a different PR to make this smaller.
Example configuration:
```yaml
managedClusterGroups:
- name: group-with-pool
clusterPools:
spokesPool:
name: spokes-pool
openshiftVersion: 4.14.12
baseDomain: domain.example.com
platform:
aws:
region: ap-southeast-2
clusters: …
```

feat: use hive clusterdeployment for creating spoke clusters

---

ansible/playbooks/auto-approve-installplans/auto-approve-installplans.yaml
clustergroup/templates/imperative/auto-approve-installplans.yaml
clustergroup/values.schema.json

Simplified version of https://github.com/validatedpatterns/common/pull/480 as nowadays the imperative service account already has cluster-admin.

Simplified PR for auto approve install plans

---

.github/workflows/chart-split.yml

Otherwise we will get errors during the command as git subtree has
regressed since v2.44.0

Use a specific git version when running git subtree split

---

ansible/roles/vault_utils/tasks/vault_spokes_init.yaml

When setting up vault we loop through all the managed clusters and set
up the token so ESO can fetch certain paths in vault. This happens in
the unseal vault ansible job and will fail if one of the managed
clusters is unreachable. This is undesirable because a cluster might
have been shut down on purpose or might be temporarily not reachable
and this is no reason to stop the configuration of vault.
1. Deployed mcg on sno1 and sno2. All green.
2. Shut off sno2 so it is unreachable. observed unseal-cronjob fail (took a while but eventually failed with:
```
TASK [vault_utils : Fetch remote ansible to remote cluster] ********************
ok: [localhost] => (item=local-cluster)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: …
```

Skip unreachable spokes when setting up vault

---

.github/workflows/linter.yml

It's the version gitops 1.12 is using these days:
❯ oc exec -it -n openshift-gitops openshift-gitops-repo-server-66bf746964-926qk -c argocd-repo-server -- bash -c "helm version"
version.BuildInfo{Version:"v3.14.0", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"", GoVersion:"go1.21.9 (Red Hat 1.21.9-1.module+el8.10.0+21671+b35c3b78)"}

Update helm version in CI to 3.14.0

---

acm/templates/policies/ocp-gitops-policy.yaml
tests/acm-industrial-edge-factory.expected.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-naked.expected.yaml
tests/acm-normal.expected.yaml

initContainers on the clusterwide argo instances on spokes rely on a
configmap called "trusted-ca-bundle" that gets created by ACM in the
openshift-gitops namespace.
Since we have no explicit guarantees about ordering, it might happen
that the argocd object gets created by acm before the configmap. This
is problematic because the init container will start but just ignore
the missing configmap.
Solve this by splitting the ocp-gitops-policy in two and making sure
that both the openshift-gitops subscription and the trusted-ca-bundle
configmap are green before applying the next dependency.

Fix initcontainer race on spokes

---

clustergroup/templates/imperative/_helpers.tpl

With the switch to initcontainers they are not used anywhere anymore

Drop imperative.volumes and imperative.volumemounts

---

ansible/plugins/modules/vault_load_parsed_secrets.py
ansible/tests/unit/test_vault_load_parsed_secrets.py

When using a password with a dollar, the oc exec commands run inside the
vault are not properly escaped, casing the dollar signed to be
interpreted by the shell inside the vault pod.
So a password like 'Y$yxn54&qXAxpUd2*yGH' will become 'Y&qXAxpUd2*yGH'
in the vault.
This is because the command that is being run ends up being:
oc exec -n vault vault-0 -i -- sh -c "vault kv patch -mount=secret global/mysecret dollar=Y$yxn54&qXAxpUd2*yGH"
The `$yxn54` will be interpreted by the shell inside vault.
Let's fix this by running a properly escaped command:
oc exec -n vault vault-0 -i -- sh -c "vault kv patch -mount=secret global/mysecret dollar='"'Y$yxn54&qXAxpUd2*yGH'"'"
Reported-By: Chris Butler <chris.butler@redhat.com>

Properly quote vault kv command

---

clustergroup/values.schema.json
operator-install/templates/pattern.yaml
operator-install/values.yaml
tests/operator-install-industrial-edge-factory.expected.yaml
tests/operator-install-industrial-edge-hub.expected.yaml
tests/operator-install-medical-diagnosis-hub.expected.yaml
tests/operator-install-naked.expected.yaml
tests/operator-install-normal.expected.yaml

We introduce the `main.git.repoUpstreamURL` parameter. This can be used
to set `originRepo`.
When `originRepo` is set, an in-cluster gitea will automatically be spawned.
In this case `originRepo` will point to the upstream repository and `targetRepo`
will point to the internal in-cluster gitea mirror.

Allow originRepo to be set via make install and main.git parameters

---

scripts/pattern-util.sh

In 98d43123834d24fafb670e4127244cddc07763d5 (Fix pki bind mount when
using podman machine) we erroneously dropped some K8S_* variables.
Reported-by: Andrew Beekhof <beekhof@redhat.com>

Fix vars that were erroneously dropped

---

clustergroup/values.schema.json

We specifically also add helmRepoUrl as it make it more discoverable,
but we stay flexible in what we accept so that things can be extended
without having to be in lockstep with the operator.

Allow more flexibility with multiSourceConfig schema

---

acm/templates/policies/ocp-gitops-policy.yaml
acm/values.yaml
operator-install/values.yaml
reference-output.yaml
tests/acm-industrial-edge-factory.expected.yaml
tests/acm-industrial-edge-hub.expected.yaml
tests/acm-medical-diagnosis-hub.expected.yaml
tests/acm-naked.expected.yaml
tests/acm-normal.expected.yaml
tests/operator-install-industrial-edge-factory.expected.yaml
tests/operator-install-industrial-edge-hub.expected.yaml
tests/operator-install-medical-diagnosis-hub.expected.yaml
tests/operator-install-naked.expected.yaml
tests/operator-install-normal.expected.yaml

It is supported all the way back to OCP 4.12
Tested on sno hub + spoke successfully

Switch to gitops-1.13

---

.github/workflows/chart-branches.yml
operator-install/.github/workflows/update-helm-repo.yml

Since at the time the folder was named operator-install and the chart
pattern-install, let's push it out to the `pattern-install-chart` repo
which is a bit clearer.

Also push any changes to operator-install to its own repo

---

clustergroup/Chart.yaml
clustergroup/values.schema.json

The "main" subsection of helm values is only used for kickstarting a
pattern. It is entirely possible to only set one value and then set the
other variables through other means (editing CRs e.g.). There is no
point on blocking this.

Drop schema required under the Main section

---

scripts/pattern-util.sh

Without this in your values-global.yaml files, the deployment with a
slimmed down common would fail as follows:
- lastTransitionTime: "2024-09-13T18:30:19Z"
message: 'Failed to load target state: failed to generate manifest for source
1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached):
common/clustergroup: app path does not exist'

Add a check to see if multisource for clustergroup is enabled

---

Makefile
scripts/pattern-util.sh

This way yq is not required on the host. Tested as follows:
* No value set (assumes default is false)
❯ cat values-global.yaml
---
global:
pattern: multicloud-gitops
options:
useCSV: false
syncPolicy: Automatic
installPlanApproval: Automatic
main:
clusterGroupName: hub
❯ ./pattern.sh make validate-prereq
make -f common/Makefile validate-prereq
You must set ".main.multiSourceConfig.enabled: true" in your 'values-global.yaml' file
because your common subfolder is the slimmed down version with no helm charts in it
make[1]: *** [common/Makefile:161: validate-prereq] Error 1
make: *** [Makefile:12: validate-prereq] …

Move the common slim + multisource test into Makefile

---

ansible/roles/vault_utils/tasks/vault_status.yaml

While this works with older ansible versions (2.15 and before), we
need to check the difference between two lists and not a list and an
item. This breaks with ansible 2.16 and onwards
Tested with newer ansible and the vault now unseals correctly.

Make sure we compare lists with lists when doing a difference

---

scripts/pattern-util.sh

When doing disconnected installations this allows for setting a single
variable pointing to the internal disconnected registry.

Introduce PATTERN_DISCONNECTED_HOME

---

Makefile

UPI or bare metal clusters may not have any storage class.
As today, the validate-cluster target in the common/Makefile fails if there's no storage class.
Is there any reason to keep this requirement so strong in the Makefile.
Fixes #607

Update Makefile to reflect a warning if no storageclass is present

---

Makefile

After slimming common down the playbook needs renaming because
collections have slightly different naming constraints. Previous error:
❯ ./pattern.sh make load-iib
make -f common/Makefile load-iib
ERROR! the playbook: rhvp.cluster_utils.iib-ci could not be found
make[1]: *** [common/Makefile:117: load-iib] Error 1
make: *** [Makefile:12: load-iib] Error 2

Fix iib loading playbook name

---

Makefile
scripts/deploy-pattern.sh

The current output is a bit daunting for first-time users as it outputs
things like the following a few times:
customresourcedefinition.apiextensions.k8s.io/patterns.gitops.hybrid-cloud-patterns.io created
configmap/patterns-operator-config created
subscription.operators.coreos.com/patterns-operator created
error: resource mapping not found for name: "rhoai-patterns-demo" namespace: "openshift-operators" from "STDIN": no matches for kind "Pattern" in version "gitops.hybrid-cloud-patterns.io/v1alpha1"
ensure CRDs are installed first
Let's switch to something a bit more user-friendly:
make -f common/Makefile operator-deploy
Checking repository:
https://github.com/mbaldessari/multicloud-gitops.git - …

Make the make install output less daunting

---

scripts/deploy-pattern.sh

Otherwise it records the exit code of the exec call which is always 0.
This now makes things error out correctly whereas previously it did not:
❯ ./pattern.sh make install
make -f common/Makefile operator-deploy
Checking repository:
https://github.com/mbaldessari/multicloud-gitops.git - branch 'debug': OK
Checking cluster:
cluster-info: OK
storageclass: OK
Installing pattern: .....Installation failed [5/5]. Error:
Pulled: quay.io/rhn_support_mbaldess/pattern-install:0.0.4
Digest: sha256:6a5431d257f4bf05d6ac91bca4f4aa010ecb1ee60d2e03c1d0984835d210a0a8
customresourcedefinition.apiextensions.k8s.io/patterns.gitops.hybrid-cloud-patterns.io unchanged
configmap/patterns-operator-config unchanged
resource …

Record the exit code at the right time

---

Makefile

Since the slimming of common this won't work anymore:
❯ make validate-schema
make -f common/Makefile validate-schema
Validating clustergroup schema of:  ./values-global.yamlError: repo common not found
make[1]: *** [common/Makefile:162: validate-schema] Error 1
make: *** [Makefile:12: validate-schema] Error 2
Fix this to use the oci helm chart:
❯ make validate-schema
make -f common/Makefile validate-schema
Validating clustergroup schema of:  ./values-global.yamlPulled: quay.io/hybridcloudpatterns/clustergroup:0.9.13
Digest: …

Fix validated-schema make target

---

Makefile

If ACM is installed the search for `applications` matches the ACM one
and not the argo one.

Fix argo-healthcheck target

---

scripts/pattern-util.sh

Since ubuntu sometimes has /etc/pki/fwupd with little else in there,
let's just bind mount /etc/pki when /etc/pki/tls exists.
This keeps Fedora-based distros running and should fix this specific
corner case observed on ubuntu.
Co-Authored-By: Akos Eros <aeros@redhat.com>
Closes: https://github.com/validatedpatterns/medical-diagnosis/issues/130

Do not bind mount /etc/pki blindly

---

Makefile
scripts/display-secrets-info.sh
scripts/load-k8s-secrets.sh
scripts/process-secrets.sh
scripts/vault-utils.sh
scripts/write-token-kubeconfig.sh

Currently, we pass the env var EXTRA_PLAYBOOK_OPTS into our utility container when running the `pattern-util.sh` script, however, we do not use it anywhere. This commit adds propagation of the env var to the `ansible-playbook` commands which could make use of it.
As an example, you could set
```sh
export EXTRA_PLAYBOOK_OPTS="-vvv"
```
which would enable verbose logging for any of the ansible playbooks when we run `./pattern.sh make <make_target>` in any of our pattern repos.

propagate the env var EXTRA_PLAYBOOK_OPTS to our ansible-playbook commands

---

README.md
scripts/make-common-subtree.sh

A few small changes in this commit:
* Update README to reference the `make-common-subtree` script in common rather than MCG repo
* Update README and `make-common-subtree` script to use same default remote name for common subtree that we use in our `update-common-everywhere` script.
* Update file name for the script to use dashes rather than underscores for consistency
* Update the name of our GH org to `validatedpatterns`

update how to make common subtree

---

Makefile
scripts/pattern-util.sh

With this one can disable the origin validation entirely.
This can come in handy when setting things up for testing the
existance of the remote branch is too onerous (i.e. private git repo)
Now you can run:
export DISABLE_VALIDATE_ORIGIN=true
and the check will be skipped

Introduce DISABLE_VALIDATE_ORIGIN variable

---

Makefile

No point in having the user set DISABLE_VALIDATE_ORIGIN=true when they
also pass a TOKEN_SECRET, just skip the validation entirely in that
case.

Disable validate_origin if a token_secret is set

---

scripts/pattern-util.sh

The quiet option only available from podman 4.3. Instead just drop the
header line and count the connections manually. This way we would still
be able to see any other errors.
resolves #637

fix: Drop the quiet from the podman system connection list cmd
