validatedpatterns/common

- site/templates/subscriptions.yaml
This reverts commit c463cbc4ae387f14889c2b5a2f24a3f0134dfb05.
This accidentally snuck into the change stream.  Sorry.
> Revert "Attempt new template format"

- Makefile
- acm/templates/managed-clusters/staging.yaml
- acm/templates/policies/application-policies.yaml
- install/templates/argocd/application.yaml
- site/templates/applications.yaml
- site/templates/argocd-super-role.yaml
- site/templates/argocd.yaml
- site/templates/gitops-namespace.yaml
- site/templates/namespaces.yaml
- site/templates/projects.yaml
Pros
- namespaced argos have reduced capabilities
- better isolation between sites
Cons
- can't see all applications in one place
- need to look up the URL and password for each argo instance
> Used a namespaced argo instance for the site applications

- install/templates/secrets/s3-secret.yaml
This is to support the S3 functionality in the Industrial Edge pattern.
> New s3 secrets file for central-s3 support

- Makefile
- scripts/vault-utils.sh
> Add an unseal target and provide it a default in the script

- Makefile
- scripts/vault-utils.sh
vault_init() now does the following:
- vault login
- vault k8s init
- vault secrets init
- vault pki init
Vault unseal also logs in after unsealing.
There is a secret_create function now too - we still would need to manage the policy as part of that, I think
> Vault initialization and secret management improvements

- tests/acm-naked.expected.yaml
- tests/acm-normal.expected.yaml
- tests/clustergroup-naked.expected.yaml
- tests/clustergroup-normal.expected.yaml
Currently we fail in a bunch of tests. Let's fix these up so we'll be
able to introduce some unit testing CI soon.
Tested with:
$ make test |grep FAIL
Testing install chart (naked)
Testing clustergroup chart (naked)
Testing acm chart (naked)
Testing install chart (normal)
Testing clustergroup chart (normal)
Testing acm chart (normal)
> Fix make test

- scripts/ansible-push-vault-secrets.sh
> Add script to push vault secrets

- .github/linters/.markdown-lint.yml
- .github/workflows/linter.yml
- tests/acm-naked.expected.yaml
- tests/acm-normal.expected.yaml
- tests/clustergroup-naked.expected.yaml
- tests/clustergroup-normal.expected.yaml
- Fix test error in clustergroup example
- Fix acm naked example test
- Fix tests/clustergroup-normal.expected.yaml test
- Add initial checking github action on every pull/push
> Add 'make test' to every common/ PR

- .github/workflows/linter.yml
- Makefile
- Add a helmlint target that runs helm lint over the charts
- Run make helmlint on every push/pull request
> Add 'make helmlint' to every common/ PR

- Makefile
- Add golang-external-secrets to the charts being tested
- Add right params to helmlint
> Add golang-secret-external to the charts to be tested

- scripts/secret.sh
Via 465b1c40 in Industrial Edge we updated common/scripts/secret.sh in
the IE repo only.
Let's bring those changes back into common and while we're at it, let's
make the indenting more consistent.
> Bring back changes to secret.sh from IE

- .github/workflows/linter.yml
- Makefile
- Add a kubeval makefile target
- Add helm kubeval task to linter
> Add kubeval target and run it in github action

- scripts/ansible-push-vault-secrets.sh
We first check for ~/.kube/config and if it also does not exist
then we bail out.
There should be no need to set anything else in the playbook as
~/.kube/config is automatically read by the ansible kubernetes.core
collection [1]
[1] https://github.com/ansible-collections/kubernetes.core/blob/main/docs/kubernetes.core.kubectl_connection.rst
> Also support oc login in the script to push secrets into the vault

- clustergroup/templates/subscriptions.yaml
- examples/values-example.yaml
- tests/clustergroup-normal.expected.yaml
- Convert the test example to non-anonymous lists
- Support easily disabling subscriptions
- Fix up helm tests
> backport andrew ie changes

- .gitignore
- clustergroup/templates/imperative/job.yaml
- Fix verbosity job attribute
- Add support for tags in imperative jobs
- Add super-linter.log to .gitignore
> Small imperative fixes/additions

- Makefile
> ux improvements

- acm/templates/policies/application-policies.yaml
- ansible/roles/vault_utils/tasks/push_secrets.yaml
- clustergroup/templates/applications.yaml
This will allow for the addition of an array of valueFiles to be added in addition to the ones clustergroup adds implicitly (specifically values-global.yaml and values-clustergroup-name.yaml).
> Add support for extraValueFiles section for applications

- acm/templates/policies/application-policies.yaml
- clustergroup/templates/applications.yaml
Add fileParameters, which we are unlikely to need, but are supported by ArgoCD
> Add fileParameters

- ansible/roles/vault_utils/tasks/vault_unseal.yaml
> Set retries for joining raft cluster

- clustergroup/templates/applications.yaml
Same change as intended in https://github.com/hybrid-cloud-patterns/common/pull/126 but since I did that on my main branch, things got weird.
> Expand pattern globals

- clustergroup/values.yaml
- tests/clustergroup-normal.expected.yaml
Because I am just that impatient and this sounds like a more reasonable
trade-off.
> Switch unsealing in the cluster from 9mins to 5mins

- examples/blank/Chart.yaml
- examples/blank/templates/manifest.yaml
- examples/blank/values.yaml
- tests/examples-blank-naked.expected.yaml
- tests/examples-blank-normal.expected.yaml
To point people to when they think creating one is hard
> Create an example blank chart

- scripts/pattern-util.sh
Add script that consumers can use to invoke https://quay.io/repository/hybridcloudpatterns/hybridcloudpatterns-utility-ee to interact with the pattern environment
> Add wrapper script to invoke pattern utility container

- clustergroup/templates/cluster-external-secrets.yaml
- examples/values-secret.yaml
- tests/clustergroup-normal.expected.yaml
> Reduce the complexity of secrets needed to drive the argo push model

- clustergroup/templates/cluster-external-secrets.yaml
- tests/clustergroup-normal.expected.yaml
> Fix external secrets template

- Makefile
Getting SSH auth to work automatically inside a container seems to be a
bit brittle as it is very dependent on OS and configuration. For now
let's just skip the ssh tests of the 'validate-origin' Makefile target
when running inside a container.
1) Without container
$ make validate-origin
make -f common/Makefile validate-origin
Checking repo https://github.com/mbaldessari/multicloud-gitops.git - branch test-git-ssh-disabling
https://github.com/mbaldessari/multicloud-gitops.git - test-git-ssh-disabling exists
2) Inside a container with the wrapper script:
$ ./common/scripts/pattern-util.sh make …
> Skip git ssh checks when running inside a container

- ansible/plugins/module_utils/load_secrets_v2.py
- ansible/roles/vault_utils/README.md
- ansible/roles/vault_utils/values-secrets.v2.schema.json
- ansible/tests/unit/test_vault_load_secrets_v2.py
- ansible/tests/unit/v2/values-secret-v2-defaultvp-policy.yaml
- ansible/tests/unit/v2/values-secret-v2-generate-base64.yaml
- ansible/tests/unit/v2/values-secret-v2-onlygenerate.yaml
- ansible/tests/unit/v2/values-secret-v2-test-override.yaml
- ansible/tests/unit/v2/values-secret-v2-wrong-override.yaml
- examples/secrets/values-secret.v2.yaml
still to be tested properly and cleaned up
> Add override attribute support

- Changes.md
- ansible/plugins/module_utils/load_secrets_v2.py
- ansible/roles/vault_utils/values-secrets.v2.schema.json
- ansible/tests/unit/test_vault_load_secrets_v2.py
- ansible/tests/unit/v2/values-secret-v2-emptyvaultprefix.yaml
- examples/secrets/values-secret.v2.yaml
This way the secret templates can be less verbose in most cases.
> Default vaultPrefixes to be ["hub"]

- ansible/plugins/module_utils/load_secrets_common.py
- ansible/plugins/module_utils/load_secrets_v2.py
- ansible/roles/vault_utils/README.md
- ansible/roles/vault_utils/values-secrets.v2.schema.json
- ansible/tests/unit/test_ini_file.py
- ansible/tests/unit/test_vault_load_secrets_v2.py
- ansible/tests/unit/v2/aws-example.ini
- ansible/tests/unit/v2/values-secret-v2-ini-file.yaml
- ansible/tests/unit/v2/values-secret-v2-wrong-ini-file.yaml
- examples/secrets/values-secret.v2.yaml
- Add a get_ini_value() commodity function
- Fix up ini function and add tests
- Add ini_file support
> Add ini-file support

- ansible/plugins/filter/parse_acm_secrets.py
- Add "vault_path" to the parse_acm_secrets filter
- Fix up some pylint warnings
> Improve vault path parse secret filter

- Changes.md
- Makefile
Let's not do it just yet. There are values files out there which might
barf needlessly
> Do not run validate-schema by default

- .github/workflows/jsonschema.yaml
- clustergroup/values.schema.json
- Make sure our readOnly attributes are proper booleans
- Drop managedClusterGroups as a required property
- Drop 'pattern' as a required property
- Run check-json schema for all yaml files under examples/
> Schema Validation Improvements

- ansible/roles/vault_utils/defaults/main.yml
- ansible/roles/vault_utils/tasks/vault_secrets_init.yaml
- ansible/roles/vault_utils/tasks/vault_spokes_init.yaml
- Add a global policy in the vault configuration
- Make sure we use specialized vars for spokes
> global policy

- Makefile
- Better help output
- Drop operator-upgrade it's the same as operator-deploy
> Better Help message

- acm/templates/policies/ocp-gitops-policy.yaml
- operator-install/crds/gitops.hybrid-cloud-patterns.io_patterns.yaml
- operator-install/templates/pattern.yaml
- operator-install/values.yaml
- reference-output.yaml
- tests/acm-industrial-edge-factory.expected.yaml
- tests/acm-industrial-edge-hub.expected.yaml
- tests/acm-medical-diagnosis-hub.expected.yaml
- tests/acm-naked.expected.yaml
- tests/acm-normal.expected.yaml
- tests/operator-install-industrial-edge-factory.expected.yaml
- tests/operator-install-industrial-edge-hub.expected.yaml
- tests/operator-install-medical-diagnosis-hub.expected.yaml
- tests/operator-install-naked.expected.yaml
- tests/operator-install-normal.expected.yaml
- Update the gitops patterns CRD
- Switch to gitops-1.8 channel in common
> gitops 1.8

- .ansible-lint
- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-unittest.yml
- .github/workflows/jsonschema.yaml
- Makefile
- ansible/playbooks/acm/acmhub-get-ca.yaml
- ansible/playbooks/hello-world/hello-world.yaml
- ansible/roles/vault_utils/tasks/push_secrets.yaml
- ansible/roles/vault_utils/tests/test.yml
- Add a hello-world ansible playbook example
- Inject ANSIBLE_CONFIG in make ansible-lint
- Use new ansible-lint action
- Fix some ansible-lint warnings
- Fix up python versions
- Skip cannot find role error
> Add Hello World imperative example

- .ansible-lint
- Changes.md
- Makefile
- operator-install/templates/pattern.yaml
- operator-install/values.yaml
- tests/operator-install-industrial-edge-factory.expected.yaml
- tests/operator-install-industrial-edge-hub.expected.yaml
- tests/operator-install-medical-diagnosis-hub.expected.yaml
- tests/operator-install-naked.expected.yaml
- tests/operator-install-normal.expected.yaml
- Set gitOpsSpec.operatorSource
- Introduce EXTRA_HELM_OPTS
> catalgSource fixes

- ansible/roles/iib_ci/README.md
- Fix typo in README for iib
- Simplify the README a bit
> Readme fixes

- golang-external-secrets/templates/golang-external-secrets-hub-presync.yaml
- golang-external-secrets/templates/golang-external-secrets-hub-vault-rbac-role.yaml
- golang-external-secrets/templates/golang-external-secrets-hub-vault-rbac-rolebinding.yaml
- golang-external-secrets/values.yaml
- tests/golang-external-secrets-industrial-edge-hub.expected.yaml
- tests/golang-external-secrets-medical-diagnosis-hub.expected.yaml
- tests/golang-external-secrets-naked.expected.yaml
- tests/golang-external-secrets-normal.expected.yaml
- WIP add presync for eso that waits for vault to be up
- Add tests
> Presync job hook

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-unittest.yml
- .github/workflows/chart-branches.yml
- .github/workflows/chart-split.yml
- .github/workflows/jsonschema.yaml
- .github/workflows/linter.yml
- .github/workflows/superlinter.yml
- clustergroup/values.schema.json
- operator-install/templates/pattern.yaml
Tested as:
$ helm template .  > /tmp/a; helm template . --set 'main.analyticsUUID=foo' > /tmp/b; diff -u /tmp/a /tmp/b
--- /tmp/a      2023-09-04 15:49:51.160607725 +0200
+++ /tmp/b      2023-09-04 15:49:51.177607813 +0200
@@ -15,6 +15,7 @@
operatorSource: redhat-operators
multiSourceConfig:
enabled: false
+  analyticsUUID: foo
> Expose UUID

- Makefile
The validate-cluster target will be in charge of doing some sanity check
on the cluster. Initially we just check the connection to the cluster
and that at least one storageclass is available to the cluster.
1) Cluster with a storageclass (LVM in my case)
$ make validate-cluster
Checking cluster:
cluster-info: OK
storageclass: OK
2) Cluster without a storageclass:
$ make validate-cluster
Checking cluster:
cluster-info: OK
storageclass: None Found
make: *** [Makefile:99: validate-cluster] Error 1
> Introduce a validate-cluster target in the install target

- ansible/roles/iib_ci/README.md
- ansible/roles/iib_ci/tasks/setup-internal-registry.yml
- Increase the wait for the internal registry
- Add a note about SNOs and internal registries
> IIB improvements

- clustergroup/Chart.yaml
We're fairly feature complete at this point in time, let's signal that
by upping the version substantially.
> Release clustergroup v0.8.0

- clustergroup/values.yaml
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-naked.expected.yaml
- tests/clustergroup-normal.expected.yaml
Tested in MCG and everything deployed correctly (imperative ansible jobs
ran without issues)
> Upgrade default imperative image

- acm/templates/policies/private-repo-policies.yaml
- clustergroup/templates/_helpers.tpl
- clustergroup/templates/imperative/_helpers.tpl
- tests/acm-industrial-edge-factory.expected.yaml
- tests/acm-industrial-edge-hub.expected.yaml
- tests/acm-medical-diagnosis-hub.expected.yaml
- tests/acm-naked.expected.yaml
- tests/acm-normal.expected.yaml
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-naked.expected.yaml
- tests/clustergroup-normal.expected.yaml
- Add support for private repos
- Amend tests
> Private repo support

- Makefile
A normal non-private deployment:
./pattern.sh make show
helm template common/operator-install/ --name-template multicloud-gitops -f values-global.yaml --set main.git.repoURL="https://github.com/mbaldessari/multicloud-gitops.git" --set main.git.revision=private-repo-cli
...
apiVersion: gitops.hybrid-cloud-patterns.io/v1alpha1
kind: Pattern
metadata:
name: multicloud-gitops
namespace: openshift-operators
spec:
clusterGroupName: hub
gitSpec:
targetRepo: https://github.com/mbaldessari/multicloud-gitops.git
targetRevision: private-repo-cli
gitOpsSpec:
operatorChannel: gitops-1.8
operatorSource: redhat-operators
multiSourceConfig:
enabled: true
analyticsUUID: vp-team-bandini
When we set the TOKEN_SECRET AND TOKEN_NAMESPACE env variables:
./pattern.sh make TOKEN_SECRET=foo TOKEN_NAMESPACE=bar …
> Add support for private repo deployments via CLI

- scripts/pattern-util.sh
- Make the container to run with the UID and GID of the user running pattern.sh
- Error out nicely if podman is not present
> Fixes and cleanups

- hashicorp-vault/values.yaml
- tests/hashicorp-vault-industrial-edge-factory.expected.yaml
- tests/hashicorp-vault-industrial-edge-hub.expected.yaml
- tests/hashicorp-vault-medical-diagnosis-hub.expected.yaml
- tests/hashicorp-vault-naked.expected.yaml
- tests/hashicorp-vault-normal.expected.yaml
This fixes a few CVEs.
Tested on MCG.
> Update vault image to 1.15.5-ubi

- scripts/pattern-util.sh
- scripts/preview.sh
- **Introduce a generic parameter override via the EXTRA_ARGS env variable**
- **Allow overriding the oc lookups in preview.sh**
> Some more fixes for preview

- scripts/preview-all.sh
- scripts/preview.sh
With this the preview all should be a lot more complete and useful.
Closes: https://github.com/validatedpatterns/common/issues/452
> Add clustergroup support to preview target

- clustergroup/values.schema.json
Not entirely sure how this slipped in.
Reported-by: Martin Jackson <mhjacks@redhat.com>
> Drop unused piece of schema json

- clustergroup/templates/_helpers.tpl
- Fixed issue in common/clustergroup/templates/_helpers.tpl to render correct label
> Namespace argocd.argoproj.io/managed-by label issue

- clustergroup/values.schema.json
This way it can be set straight from a values-*.yaml file
Tested on MCG.
> Add main.experimentalCapabilities to values.schema.json

- acm/templates/policies/application-policies.yaml
- tests/acm-industrial-edge-hub.expected.yaml
- tests/acm-medical-diagnosis-hub.expected.yaml
- tests/acm-normal.expected.yaml
- **Fix up tests after upstream PR merge**
- **Drop old comments**
> Small cleanups

- clustergroup/templates/_helpers.tpl
- clustergroup/templates/core/operatorgroup.yaml
- clustergroup/templates/plumbing/applications.yaml
- tests/acm-industrial-edge-hub.expected.yaml
- tests/acm-medical-diagnosis-hub.expected.yaml
- tests/acm-normal.expected.yaml
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-normal.expected.yaml
- **bug: Fix for multiple OperatorGroup rendering**
> helper operatorgroup fix

- acm/templates/multiclusterhub.yaml
- acm/values.yaml
- ansible/roles/iib_ci/README.md
- tests/acm-industrial-edge-factory.expected.yaml
- **Add overrides for MCE IIB**
- **Update README for IIB changes**
> acm iib overrides

- .github/workflows/chart-branches.yml
This should fix the fact that jobs are triggered on unrelated changes
> Make sure that the if condition on chart split is not always true

- acm/templates/policies/application-policies.yaml
- acm/templates/policies/ocp-gitops-policy.yaml
- clustergroup/templates/imperative/auto-approve-installplans.yaml
- clustergroup/templates/imperative/job.yaml
- clustergroup/templates/imperative/unsealjob.yaml
- clustergroup/templates/plumbing/argocd.yaml
- tests/acm-industrial-edge-factory.expected.yaml
- tests/acm-industrial-edge-hub.expected.yaml
- tests/acm-medical-diagnosis-hub.expected.yaml
- tests/acm-naked.expected.yaml
- tests/acm-normal.expected.yaml
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-naked.expected.yaml
- tests/clustergroup-normal.expected.yaml
- **Drop initContainers variable and make it the default**
- **Update tests after dropping initContainers**
> Make initContainers the default

- clustergroup/templates/imperative/_helpers.tpl
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-naked.expected.yaml
- tests/clustergroup-normal.expected.yaml
- **Drop imperative.initcontainers.gitinit**
- **Have unseal work whenever we specifiy HEAD**
> Make unseal HEAD work

- clustergroup/templates/plumbing/argocd.yaml
- clustergroup/values.schema.json
- clustergroup/values.yaml
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-naked.expected.yaml
- tests/clustergroup-normal.expected.yaml
- **make resourceExclusion configurable**
- **Update tests after upgrading resourceExclusions tweak**
> Make healthchecks configurable

- clustergroup/values.schema.json
- clustergroup/values.yaml
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-naked.expected.yaml
- tests/clustergroup-normal.expected.yaml
- **Make resourcehealthchecks configurable**
- **Update tests after upgrading resourceHealthChecks change**
> Make resourcehealthchecks configurable

- clustergroup/templates/imperative/_helpers.tpl
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-naked.expected.yaml
- tests/clustergroup-normal.expected.yaml
Otherwise we might error out with:
error: unknown option `branch qe_test-16831'
usage: git clone [<options>] [--] <repo> [<dir>]
> Do not quote $BRANCH variable

- acm/templates/policies/acm-hub-ca-policy.yaml
- acm/templates/policies/ocp-gitops-policy.yaml
- clustergroup/templates/imperative/_helpers.tpl
- clustergroup/templates/plumbing/argocd.yaml
- tests/acm-industrial-edge-factory.expected.yaml
- tests/acm-industrial-edge-hub.expected.yaml
- tests/acm-medical-diagnosis-hub.expected.yaml
- tests/acm-naked.expected.yaml
- tests/acm-normal.expected.yaml
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-naked.expected.yaml
- tests/clustergroup-normal.expected.yaml
- **Make HUB work when spokes point to in hub cluster gitea**
- **update tests**
> Support for gitea on spokes

- acm/Chart.yaml
- golang-external-secrets/Chart.yaml
- hashicorp-vault/Chart.yaml
- **ACM chart version 0.0.2**
- **golang-external-secrets chart version 0.0.4**
- **hashicorp-vault chart version 0.0.2**
> Update chart versions

- acm/templates/_helpers.tpl
- acm/templates/policies/application-policies.yaml
- clustergroup/templates/_helpers.tpl
- tests/acm-industrial-edge-hub.expected.yaml
- tests/acm-medical-diagnosis-hub.expected.yaml
- tests/acm-normal.expected.yaml
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-normal.expected.yaml
- **Implement multi-source**
- **Add tests for proper multisource support on spokes**
> Multisource on spokes

- .ansible-lint
- Makefile
- ansible/playbooks/write-token-kubeconfig/write-token-kubeconfig.yml
- scripts/pattern-util.sh
- scripts/write-token-kubeconfig.sh
- scripts/write-token-kubeconfig.yml
This provides a makefile target to make a kubeconfig file under specific conditions. It depends on the ansible collection community.okd so depends on https://github.com/validatedpatterns/utility-container/pull/41 being merged first
> Provide kubeconfig writer

- scripts/pattern-util.sh
Currently we test for the existance of local TLS folder and bind mount
them in containers. This does not work correctly when using podman
machine, because a the test is running on the host and so we might bind
mount the wrong folder. For example:
On Mac OSX /etc/pki does not exist on the folder and so we bind mount
/etc/ssl even though /etc/pki does exist in the podman machine VM
Co-Authored-By: Ákos Erős <aeros@redhat.com>
> Fix pki bind mount when using podman machine

- scripts/pattern-util.sh
The $subj pr fixes an issue with the passwd entry created in `/etc/passwd` which was causing issues when folks are cloning with ssh
> resolves #21 rag-llm-gitops

- scripts/pattern-util.sh
Since it can be used to point to an alternative file, let's inject it
into the container
> Inject VALUES_SECRET env var

- acm/Chart.yaml
- acm/templates/policies/ocp-gitops-policy.yaml
- clustergroup/Chart.yaml
- **Allow overriding gitops source on spokes**
- **Update acm chart to v0.1.1**
- **Update clustergroup chart to 0.8.11**
> A couple of small updated and new releases

- acm/templates/provision/clusterpool.yaml
- tests/acm-normal.expected.yaml
Closes: validatedpatterns/regional-resiliency-pattern#5
> Use $group.name in clusterset metadata

- acm/templates/_helpers.tpl
- clustergroup/templates/_helpers.tpl
- tests/acm-industrial-edge-hub.expected.yaml
- tests/acm-medical-diagnosis-hub.expected.yaml
- tests/acm-normal.expected.yaml
- tests/clustergroup-industrial-edge-factory.expected.yaml
- tests/clustergroup-industrial-edge-hub.expected.yaml
- tests/clustergroup-medical-diagnosis-hub.expected.yaml
- tests/clustergroup-normal.expected.yaml
- **Expose originURL as helm value**
- **Update tests after common rebase**
> expose origin

- scripts/manage-secret-app.sh
- scripts/preview.sh
- **Update secret backend change script**
- **Update preview script**
> Fix scripts after common slim

- Makefile
If we set the main.git.upstreamRepoURL then we need to check that one
for the presence of the branch and not whatever is configured as the
origin remote.
- Working upstreamRepoURL:
❯ yq -r '.main.git.repoUpstreamURL // (.main.git.repoUpstreamURL = "")' values-global.yaml
https://github.com/mbaldessari/industrial-edge
❯ make validate-origin
make -f common/Makefile validate-origin
make[1]: Entering directory '/home/michele/Engineering/cloud-patterns/industrial-edge'
Checking repository:
Upstream URL set to: https://github.com/mbaldessari/industrial-edge
https://github.com/mbaldessari/industrial-edge - branch 'for-max-s3-kafka-fix': OK
make[1]: Leaving directory '/home/michele/Engineering/cloud-patterns/industrial-edge'
- upstreamRepoURL without the branch:
❯ yq -r …
> Improve validate-origin
